import { FormEvent, useMemo, useState } from 'react';
import { ManagementModal } from '../../management/components/ManagementModal';
import { PROCESS_STAGE_LABELS, type VisaProcess } from '../../processes/types/process';
import { DocumentChecklistForm } from '../components/DocumentChecklistForm';
import { DocumentTable } from '../components/DocumentTable';
import type { DocumentItem } from '../types/document';

type DocumentUpdate = Partial<Pick<DocumentItem, 'processId' | 'title' | 'required' | 'received' | 'notes'>>;
type DocumentsPageProps = { processes: VisaProcess[]; documents: DocumentItem[]; onCreateDocument: (input: Omit<DocumentItem, 'id' | 'updatedAt'>) => void; onUpdateDocument: (documentId: string, patch: DocumentUpdate) => void; onToggleReceived: (documentId: string) => void; showForm: boolean; onCloseForm: () => void; };

export function DocumentsPage({ processes, documents, onCreateDocument, onUpdateDocument, onToggleReceived, showForm, onCloseForm }: DocumentsPageProps) {
  const [processFilter, setProcessFilter] = useState('all'); const [viewDocument,setViewDocument]=useState<DocumentItem>(); const [editDocument,setEditDocument]=useState<DocumentItem>(); const [editTitle,setEditTitle]=useState(''); const [editProcessId,setEditProcessId]=useState(''); const [editRequired,setEditRequired]=useState(true); const [editReceived,setEditReceived]=useState(false); const [editNotes,setEditNotes]=useState('');
  const required = documents.filter((document) => document.required).length; const received = documents.filter((document) => document.received).length; const pending = documents.filter((document) => document.required && !document.received).length; const filteredDocuments = useMemo(() => processFilter === 'all' ? documents : documents.filter((document)=>document.processId===processFilter), [documents,processFilter]);
  const processProgress = processes.map((process)=>{ const items=documents.filter((document)=>document.processId===process.id); const requiredItems=items.filter((document)=>document.required); const receivedRequired=requiredItems.filter((document)=>document.received).length; const progress=requiredItems.length?Math.round((receivedRequired/requiredItems.length)*100):0; return {process,items:items.length,pending:requiredItems.length-receivedRequired,progress}; });
  function beginEdit(document:DocumentItem){setEditDocument(document);setEditTitle(document.title);setEditProcessId(document.processId);setEditRequired(document.required);setEditReceived(document.received);setEditNotes(document.notes)}
  function saveEdit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editDocument||editTitle.trim().length<2||!editProcessId)return;onUpdateDocument(editDocument.id,{title:editTitle.trim(),processId:editProcessId,required:editRequired,received:editReceived,notes:editNotes.trim()});setEditDocument(undefined)}
  function createDocument(input:Omit<DocumentItem,'id'|'updatedAt'>){onCreateDocument(input);onCloseForm()}

  return <section className="management-page document-page" aria-labelledby="documents-title"><div className="management-page__heading management-page__heading--row"><div><span className="management-eyebrow">Controle documental</span><h1 id="documents-title">Documentos</h1><p>Organize o checklist de cada processo e acompanhe rapidamente itens obrigatórios, recebidos e pendentes.</p></div>{processes.length>0&&<label className="document-process-filter"><span>Filtrar processo</span><select value={processFilter} onChange={(event)=>setProcessFilter(event.target.value)}><option value="all">Todos os processos</option>{processes.map((process)=><option key={process.id} value={process.id}>{process.category} · {PROCESS_STAGE_LABELS[process.stage]}</option>)}</select></label>}</div>
  <div className="document-summary-grid"><article><span>Total de itens</span><strong>{documents.length}</strong><small>Checklist desta sessão</small></article><article><span>Obrigatórios</span><strong>{required}</strong><small>Itens exigidos no processo</small></article><article><span>Recebidos</span><strong>{received}</strong><small>Documentos marcados como recebidos</small></article><article><span>Pendentes</span><strong>{pending}</strong><small>Obrigatórios ainda não recebidos</small></article></div>
  {processes.length>0&&<section className="document-progress-card"><div className="document-progress-card__heading"><div><span className="management-eyebrow">Progresso documental</span><h2>Por processo</h2></div><span>{processProgress.length} processo(s)</span></div><div className="document-progress-list">{processProgress.map(({process,items,pending,progress})=><a href={`/app/processos/${encodeURIComponent(process.id)}`} key={process.id}><div><strong>{process.category}</strong><small>{PROCESS_STAGE_LABELS[process.stage]} · {items} item(ns) · {pending} pendência(s)</small></div><div className="document-progress-meter"><i style={{width:`${progress}%`}} /></div><span>{progress}%</span></a>)}</div></section>}
  {processes.length===0&&<div className="document-prerequisite"><div><span className="management-eyebrow">Pré-requisito</span><h2>Crie um processo antes do checklist</h2><p>Os documentos são organizados por processo para manter contexto e rastreabilidade.</p></div><a className="management-primary-button" href="/app/processos">Ir para Processos</a></div>}
  <section className="document-list-card"><div className="document-list-card__heading"><div><span className="management-eyebrow">Checklist</span><h2>{processFilter==='all'?'Itens documentais':'Itens do processo selecionado'}</h2></div><span>{filteredDocuments.length} registro(s)</span></div><DocumentTable processes={processes} documents={filteredDocuments} onToggleReceived={onToggleReceived} onView={setViewDocument} onEdit={beginEdit} /></section>

  <ManagementModal open={showForm&&processes.length>0} onClose={onCloseForm} eyebrow="Checklist" title="Adicionar documento" subtitle="Inclua um item documental sem sair da listagem."><DocumentChecklistForm processes={processes} onCreateDocument={createDocument} /></ManagementModal>
  <ManagementModal open={Boolean(viewDocument)} onClose={()=>setViewDocument(undefined)} eyebrow="Visualização" title={viewDocument?.title??'Documento'} size="md">{viewDocument&&<div className="management-modal-view"><div className="management-modal-view__grid"><div className="management-modal-view__field"><span>Processo</span><strong>{processes.find((p)=>p.id===viewDocument.processId)?.category??'Processo não encontrado'}</strong></div><div className="management-modal-view__field"><span>Obrigatório</span><strong>{viewDocument.required?'Sim':'Não'}</strong></div><div className="management-modal-view__field"><span>Situação</span><strong>{viewDocument.received?'Recebido':'Pendente'}</strong></div><div className="management-modal-view__field"><span>Atualizado</span><strong>{new Date(viewDocument.updatedAt).toLocaleString('pt-BR')}</strong></div><div className="management-modal-view__field management-modal-view__field--full"><span>Observações</span><p>{viewDocument.notes||'Sem observações.'}</p></div></div><div className="management-form-actions"><button className="management-primary-button" type="button" onClick={()=>{setViewDocument(undefined);beginEdit(viewDocument)}}>Editar documento</button></div></div>}</ManagementModal>
  <ManagementModal open={Boolean(editDocument)} onClose={()=>setEditDocument(undefined)} eyebrow="Editar documento" title={editDocument?.title??'Documento'}><form className="management-form-card" onSubmit={saveEdit}><div className="management-form-grid"><label><span>Processo</span><select value={editProcessId} onChange={(e)=>setEditProcessId(e.target.value)}>{processes.map((p)=><option key={p.id} value={p.id}>{p.category}</option>)}</select></label><label><span>Documento</span><input value={editTitle} onChange={(e)=>setEditTitle(e.target.value)} /></label><label className="management-checkbox"><input type="checkbox" checked={editRequired} onChange={(e)=>setEditRequired(e.target.checked)} /><span>Item obrigatório</span></label><label className="management-checkbox"><input type="checkbox" checked={editReceived} onChange={(e)=>setEditReceived(e.target.checked)} /><span>Documento recebido</span></label><label className="management-field--full"><span>Observações</span><textarea rows={3} value={editNotes} onChange={(e)=>setEditNotes(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-secondary-button" type="button" onClick={()=>setEditDocument(undefined)}>Cancelar</button><button className="management-primary-button" type="submit">Salvar alterações</button></div></form></ManagementModal>
  </section>;
}
