import type { Client } from '../../clients/types/client';
import { PROCESS_STAGE_LABELS, type VisaProcess } from '../../processes/types/process';
import type { ServiceInteraction } from '../types/interaction';
import { INTERACTION_CHANNEL_LABELS } from './InteractionForm';

type InteractionTimelineProps = { clients: Client[]; processes: VisaProcess[]; interactions: ServiceInteraction[]; onView: (interaction: ServiceInteraction) => void; onEdit: (interaction: ServiceInteraction) => void; };

export function InteractionTimeline({ clients, processes, interactions, onView, onEdit }: InteractionTimelineProps) {
  if (interactions.length === 0) return <div className="management-empty-state interaction-empty-state"><span className="interaction-empty-state__icon">AT</span><strong>Nenhum atendimento na sessão.</strong><span>Use o VisaChat para conversas contínuas ou registre aqui reuniões, ligações, e-mails e outros contatos relevantes.</span></div>;
  return <div className="interaction-timeline">{interactions.map((interaction) => { const client = clients.find((item) => item.id === interaction.clientId); const process = processes.find((item) => item.id === interaction.processId); return <article className="interaction-timeline__item" key={interaction.id}><div className="interaction-timeline__rail"><span>{INTERACTION_CHANNEL_LABELS[interaction.channel]}</span><i /></div><div className="interaction-timeline__content"><div className="interaction-timeline__header"><div><strong>{interaction.subject}</strong><small>{client ? <a href={`/app/clientes/${encodeURIComponent(client.id)}`}>{client.fullName}</a> : 'Cliente não encontrado'} · {new Date(interaction.occurredAt).toLocaleString('pt-BR')}</small></div>{process && <a className="interaction-process-pill" href={`/app/processos/${encodeURIComponent(process.id)}`}>{process.category} · {PROCESS_STAGE_LABELS[process.stage]}</a>}</div><p>{interaction.notes}</p><div className="management-row-actions"><button className="management-row-action" type="button" onClick={()=>onView(interaction)}>Ver</button><button className="management-row-action management-row-action--primary" type="button" onClick={()=>onEdit(interaction)}>Editar</button></div></div></article>; })}</div>;
}
