import { FormEvent, useMemo, useState } from 'react';
import type { Client } from '../../clients/types/client';
import type { VisaProcess } from '../../processes/types/process';
import { FINANCIAL_ENTRY_STATUS_LABELS, FINANCIAL_ENTRY_TYPE_LABELS, type FinancialEntry, type FinancialEntryStatus, type FinancialEntryType } from '../types/finance';

type FinancePageProps = { clients: Client[]; processes: VisaProcess[]; entries: FinancialEntry[]; onCreateEntry: (input: Omit<FinancialEntry, 'id' | 'createdAt'>) => void; };
function formatCurrency(valueCents: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(valueCents / 100); }

export function FinancePage({ clients, processes, entries, onCreateEntry }: FinancePageProps) {
  const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [type, setType] = useState<FinancialEntryType>('income'); const [status, setStatus] = useState<FinancialEntryStatus>('planned'); const [clientId, setClientId] = useState(''); const [processId, setProcessId] = useState(''); const [dueDate, setDueDate] = useState('');
  const totals = useMemo(() => { const income = entries.filter((entry) => entry.type === 'income').reduce((sum, entry) => sum + entry.amountCents, 0); const expense = entries.filter((entry) => entry.type === 'expense').reduce((sum, entry) => sum + entry.amountCents, 0); return { income, expense, balance: income - expense }; }, [entries]);
  const availableProcesses = processes.filter((process) => !clientId || process.clientId === clientId);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalized = Number(amount.replace(',', '.')); if (!Number.isFinite(normalized) || normalized <= 0) return; onCreateEntry({ description: description.trim(), amountCents: Math.round(normalized * 100), type, status, clientId: clientId || undefined, processId: processId || undefined, dueDate }); setDescription(''); setAmount(''); setDueDate(''); }
  return <section className="management-page finance-page" aria-labelledby="finance-title">
    <div className="management-page__heading management-page__heading--row"><div><span className="management-eyebrow">Controle financeiro</span><h1 id="finance-title">Financeiro</h1><p>Receitas e despesas relacionadas à operação e, quando aplicável, a clientes e processos.</p></div><span className="management-status">Frontend · sessão</span></div>
    <div className="finance-summary"><article className="finance-summary__card finance-summary__card--income"><span>Receitas</span><strong>{formatCurrency(totals.income)}</strong><small>{entries.filter((entry)=>entry.type==='income').length} lançamento(s)</small></article><article className="finance-summary__card finance-summary__card--expense"><span>Despesas</span><strong>{formatCurrency(totals.expense)}</strong><small>{entries.filter((entry)=>entry.type==='expense').length} lançamento(s)</small></article><article className="finance-summary__card finance-summary__card--balance"><span>Resultado</span><strong>{formatCurrency(totals.balance)}</strong><small>Receitas menos despesas</small></article></div>
    <div className="management-session-note">Valores são temporários e não representam faturamento real. Cobrança, conciliação, impostos e integração bancária não são simulados.</div>
    <form className="management-form-card finance-form" onSubmit={submit}><div className="management-form-grid"><label><span>Descrição</span><input required value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Ex.: honorários de assessoria" /></label><label><span>Valor (R$)</span><input required inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0,00" /></label><label><span>Tipo</span><select value={type} onChange={(e) => setType(e.target.value as FinancialEntryType)}>{Object.entries(FINANCIAL_ENTRY_TYPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value as FinancialEntryStatus)}>{Object.entries(FINANCIAL_ENTRY_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Cliente</span><select value={clientId} onChange={(e) => { setClientId(e.target.value); setProcessId(''); }}><option value="">Sem cliente específico</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label><span>Processo</span><select value={processId} onChange={(e) => setProcessId(e.target.value)}><option value="">Sem processo específico</option>{availableProcesses.map((process) => <option key={process.id} value={process.id}>{process.category}</option>)}</select></label><label><span>Vencimento</span><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-primary-button" type="submit">Adicionar lançamento</button></div></form>
    {entries.length === 0 ? <div className="management-empty-state"><strong>Nenhum lançamento na sessão.</strong><span>Registre uma receita ou despesa para validar a visão financeira.</span></div> : <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Status</th><th>Valor</th><th>Vencimento</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td><strong>{entry.description}</strong></td><td>{FINANCIAL_ENTRY_TYPE_LABELS[entry.type]}</td><td><span className="management-badge">{FINANCIAL_ENTRY_STATUS_LABELS[entry.status]}</span></td><td>{formatCurrency(entry.amountCents)}</td><td>{entry.dueDate ? new Date(`${entry.dueDate}T00:00:00`).toLocaleDateString('pt-BR') : '—'}</td></tr>)}</tbody></table></div>}
  </section>;
}
