import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { Client } from '../../clients/types/client';
import { ManagementModal } from '../../management/components/ManagementModal';
import type { VisaProcess } from '../../processes/types/process';
import { FINANCIAL_ENTRY_STATUS_LABELS, FINANCIAL_ENTRY_TYPE_LABELS, type FinancialEntry, type FinancialEntryStatus, type FinancialEntryType } from '../types/finance';

type FinancialUpdate = Partial<Pick<FinancialEntry, 'description' | 'amountCents' | 'type' | 'status' | 'clientId' | 'processId' | 'dueDate'>>;
type FinancePageProps = { clients: Client[]; processes: VisaProcess[]; entries: FinancialEntry[]; onCreateEntry: (input: Omit<FinancialEntry, 'id' | 'createdAt'>) => void; onUpdateEntry: (entryId: string, patch: FinancialUpdate) => void; showForm: boolean; onCloseForm: () => void; };
type FinanceFilter = 'all' | 'income' | 'expense' | 'planned' | 'paid';
function formatCurrency(valueCents: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(valueCents / 100); }

export function FinancePage({ clients, processes, entries, onCreateEntry, onUpdateEntry, showForm, onCloseForm }: FinancePageProps) {
  const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [type, setType] = useState<FinancialEntryType>('income'); const [status, setStatus] = useState<FinancialEntryStatus>('planned'); const [clientId, setClientId] = useState(''); const [processId, setProcessId] = useState(''); const [dueDate, setDueDate] = useState(''); const [filter, setFilter] = useState<FinanceFilter>('all'); const [error, setError] = useState(''); const [viewEntry, setViewEntry] = useState<FinancialEntry>(); const [editEntry, setEditEntry] = useState<FinancialEntry>();
  const [editDescription,setEditDescription]=useState(''); const [editAmount,setEditAmount]=useState(''); const [editType,setEditType]=useState<FinancialEntryType>('income'); const [editStatus,setEditStatus]=useState<FinancialEntryStatus>('planned'); const [editClientId,setEditClientId]=useState(''); const [editProcessId,setEditProcessId]=useState(''); const [editDueDate,setEditDueDate]=useState('');
  useEffect(()=>{if(!editEntry)return;setEditDescription(editEntry.description);setEditAmount(String(editEntry.amountCents/100).replace('.',','));setEditType(editEntry.type);setEditStatus(editEntry.status);setEditClientId(editEntry.clientId??'');setEditProcessId(editEntry.processId??'');setEditDueDate(editEntry.dueDate);},[editEntry]);
  const totals = useMemo(() => { const income = entries.filter((entry) => entry.type === 'income').reduce((sum, entry) => sum + entry.amountCents, 0); const expense = entries.filter((entry) => entry.type === 'expense').reduce((sum, entry) => sum + entry.amountCents, 0); const received = entries.filter((entry) => entry.type === 'income' && entry.status === 'paid').reduce((sum, entry) => sum + entry.amountCents, 0); const paidExpenses = entries.filter((entry) => entry.type === 'expense' && entry.status === 'paid').reduce((sum, entry) => sum + entry.amountCents, 0); const plannedIncome = entries.filter((entry) => entry.type === 'income' && entry.status === 'planned').reduce((sum, entry) => sum + entry.amountCents, 0); return { income, expense, received, paidExpenses, plannedIncome, projectedBalance: income - expense, realizedBalance: received - paidExpenses }; }, [entries]);
  const filteredEntries = useMemo(() => entries.filter((entry) => filter === 'all' || entry.type === filter || entry.status === filter), [entries, filter]); const availableProcesses = processes.filter((process) => !clientId || process.clientId === clientId); const editAvailableProcesses = processes.filter((process) => !editClientId || process.clientId === editClientId);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalizedDescription = description.trim(); const normalizedAmount = Number(amount.replace(',', '.')); if (normalizedDescription.length < 2) { setError('Informe uma descrição para a movimentação.'); return; } if (!Number.isFinite(normalizedAmount) || normalizedAmount <= 0) { setError('Informe um valor maior que zero.'); return; } onCreateEntry({ description: normalizedDescription, amountCents: Math.round(normalizedAmount * 100), type, status, clientId: clientId || undefined, processId: processId || undefined, dueDate }); setDescription(''); setAmount(''); setDueDate(''); setError(''); onCloseForm(); }
  function saveEdit(event: FormEvent<HTMLFormElement>){event.preventDefault();if(!editEntry)return;const parsed=Number(editAmount.replace(',','.'));if(editDescription.trim().length<2||!Number.isFinite(parsed)||parsed<=0)return;onUpdateEntry(editEntry.id,{description:editDescription.trim(),amountCents:Math.round(parsed*100),type:editType,status:editStatus,clientId:editClientId||undefined,processId:editProcessId||undefined,dueDate:editDueDate});setEditEntry(undefined);}

  return <section className="management-page finance-page" aria-labelledby="finance-title">
    <div className="management-page__heading"><div><span className="management-eyebrow">Controle financeiro</span><h1 id="finance-title">Financeiro</h1><p>Livro operacional de receitas e despesas relacionadas à assessoria, com vínculo opcional ao cliente e ao processo.</p></div></div>
    <div className="finance-hero"><div><span className="management-eyebrow">Resultado realizado</span><strong>{formatCurrency(totals.realizedBalance)}</strong><p>Somente lançamentos marcados como pagos entram neste saldo. Valores previstos aparecem separadamente.</p></div><div className="finance-hero__split"><article><span>Recebido</span><strong>{formatCurrency(totals.received)}</strong></article><article><span>Despesas pagas</span><strong>{formatCurrency(totals.paidExpenses)}</strong></article><article><span>A receber</span><strong>{formatCurrency(totals.plannedIncome)}</strong></article></div></div>
    <div className="finance-summary"><article className="finance-summary__card finance-summary__card--income"><span>Receitas totais</span><strong>{formatCurrency(totals.income)}</strong><small>{entries.filter((entry)=>entry.type==='income').length} lançamento(s)</small></article><article className="finance-summary__card finance-summary__card--expense"><span>Despesas totais</span><strong>{formatCurrency(totals.expense)}</strong><small>{entries.filter((entry)=>entry.type==='expense').length} lançamento(s)</small></article><article className="finance-summary__card finance-summary__card--balance"><span>Resultado projetado</span><strong>{formatCurrency(totals.projectedBalance)}</strong><small>Receitas menos despesas, independente do status</small></article></div>
    <div className="management-session-note">Valores são temporários e não representam faturamento contábil real. Cobrança, conciliação, impostos e integração bancária não são simulados.</div>
    <section className="finance-ledger-card"><div className="finance-ledger-card__heading"><div><span className="management-eyebrow">Livro da sessão</span><h2>Movimentações</h2></div><span>{filteredEntries.length} item(ns)</span></div><div className="finance-filters"><button className={filter === 'all' ? 'is-active' : ''} onClick={() => setFilter('all')} type="button">Todas</button><button className={filter === 'income' ? 'is-active' : ''} onClick={() => setFilter('income')} type="button">Receitas</button><button className={filter === 'expense' ? 'is-active' : ''} onClick={() => setFilter('expense')} type="button">Despesas</button><button className={filter === 'planned' ? 'is-active' : ''} onClick={() => setFilter('planned')} type="button">Previstas</button><button className={filter === 'paid' ? 'is-active' : ''} onClick={() => setFilter('paid')} type="button">Pagas</button></div>{filteredEntries.length === 0 ? <div className="management-empty-state"><strong>Nenhum lançamento neste filtro.</strong><span>Registre uma receita ou despesa para começar a validar a visão financeira.</span></div> : <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Descrição</th><th>Vínculo</th><th>Tipo</th><th>Status</th><th>Valor</th><th>Vencimento</th><th>Ações</th></tr></thead><tbody>{filteredEntries.map((entry) => { const client = clients.find((item) => item.id === entry.clientId); const process = processes.find((item) => item.id === entry.processId); return <tr key={entry.id}><td><strong>{entry.description}</strong></td><td>{client?.fullName ?? '—'}{process && <small>{process.category}</small>}</td><td><span className={`finance-type finance-type--${entry.type}`}>{FINANCIAL_ENTRY_TYPE_LABELS[entry.type]}</span></td><td>{FINANCIAL_ENTRY_STATUS_LABELS[entry.status]}</td><td><strong className={entry.type === 'income' ? 'finance-value finance-value--income' : 'finance-value finance-value--expense'}>{entry.type === 'income' ? '+' : '-'}{formatCurrency(entry.amountCents)}</strong></td><td>{entry.dueDate ? new Date(`${entry.dueDate}T00:00:00`).toLocaleDateString('pt-BR') : '—'}</td><td><div className="management-row-actions"><button className="management-row-action" type="button" onClick={()=>setViewEntry(entry)}>Ver</button><button className="management-row-action management-row-action--primary" type="button" onClick={()=>setEditEntry(entry)}>Editar</button></div></td></tr>; })}</tbody></table></div>}</section>

    <ManagementModal open={showForm} onClose={onCloseForm} eyebrow="Novo lançamento" title="Adicionar lançamento" subtitle="Registre uma receita ou despesa sem sair da página."><form className="management-form-card" onSubmit={submit} noValidate>{error && <div className="management-form-error" role="alert">{error}</div>}<div className="management-form-grid"><label><span>Descrição</span><input value={description} onChange={(e)=>{setDescription(e.target.value);setError('')}} /></label><label><span>Valor (R$)</span><input inputMode="decimal" value={amount} onChange={(e)=>{setAmount(e.target.value);setError('')}} placeholder="0,00" /></label><label><span>Tipo</span><select value={type} onChange={(e)=>setType(e.target.value as FinancialEntryType)}>{Object.entries(FINANCIAL_ENTRY_TYPE_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Status</span><select value={status} onChange={(e)=>setStatus(e.target.value as FinancialEntryStatus)}>{Object.entries(FINANCIAL_ENTRY_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Cliente</span><select value={clientId} onChange={(e)=>{setClientId(e.target.value);setProcessId('')}}><option value="">Sem cliente específico</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label><span>Processo</span><select value={processId} onChange={(e)=>setProcessId(e.target.value)}><option value="">Sem processo específico</option>{availableProcesses.map((process)=><option key={process.id} value={process.id}>{process.category}</option>)}</select></label><label><span>Vencimento</span><input type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-secondary-button" type="button" onClick={onCloseForm}>Cancelar</button><button className="management-primary-button" type="submit">Adicionar lançamento</button></div></form></ManagementModal>
    <ManagementModal open={Boolean(viewEntry)} onClose={()=>setViewEntry(undefined)} eyebrow="Visualização" title={viewEntry?.description ?? 'Lançamento'} size="md">{viewEntry&&<div className="management-modal-view"><div className="management-modal-view__grid"><div className="management-modal-view__field"><span>Tipo</span><strong>{FINANCIAL_ENTRY_TYPE_LABELS[viewEntry.type]}</strong></div><div className="management-modal-view__field"><span>Status</span><strong>{FINANCIAL_ENTRY_STATUS_LABELS[viewEntry.status]}</strong></div><div className="management-modal-view__field"><span>Valor</span><strong>{formatCurrency(viewEntry.amountCents)}</strong></div><div className="management-modal-view__field"><span>Vencimento</span><strong>{viewEntry.dueDate?new Date(`${viewEntry.dueDate}T00:00:00`).toLocaleDateString('pt-BR'):'Não definido'}</strong></div><div className="management-modal-view__field"><span>Cliente</span><strong>{clients.find((c)=>c.id===viewEntry.clientId)?.fullName??'Sem cliente'}</strong></div><div className="management-modal-view__field"><span>Processo</span><strong>{processes.find((p)=>p.id===viewEntry.processId)?.category??'Sem processo'}</strong></div></div><div className="management-form-actions"><button className="management-primary-button" type="button" onClick={()=>{setViewEntry(undefined);setEditEntry(viewEntry)}}>Editar lançamento</button></div></div>}</ManagementModal>
    <ManagementModal open={Boolean(editEntry)} onClose={()=>setEditEntry(undefined)} eyebrow="Editar lançamento" title={editEntry?.description??'Lançamento'}><form className="management-form-card" onSubmit={saveEdit}><div className="management-form-grid"><label><span>Descrição</span><input value={editDescription} onChange={(e)=>setEditDescription(e.target.value)} /></label><label><span>Valor (R$)</span><input inputMode="decimal" value={editAmount} onChange={(e)=>setEditAmount(e.target.value)} /></label><label><span>Tipo</span><select value={editType} onChange={(e)=>setEditType(e.target.value as FinancialEntryType)}>{Object.entries(FINANCIAL_ENTRY_TYPE_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Status</span><select value={editStatus} onChange={(e)=>setEditStatus(e.target.value as FinancialEntryStatus)}>{Object.entries(FINANCIAL_ENTRY_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Cliente</span><select value={editClientId} onChange={(e)=>{setEditClientId(e.target.value);setEditProcessId('')}}><option value="">Sem cliente específico</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label><span>Processo</span><select value={editProcessId} onChange={(e)=>setEditProcessId(e.target.value)}><option value="">Sem processo específico</option>{editAvailableProcesses.map((process)=><option key={process.id} value={process.id}>{process.category}</option>)}</select></label><label><span>Vencimento</span><input type="date" value={editDueDate} onChange={(e)=>setEditDueDate(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-secondary-button" type="button" onClick={()=>setEditEntry(undefined)}>Cancelar</button><button className="management-primary-button" type="submit">Salvar alterações</button></div></form></ManagementModal>
  </section>;
}
