import type { CmsDocument } from './types';
import { formatDate, go } from './siteCmsUtils';
import { StatusBadge } from './CmsEditors';

export function OverviewView({document,onOpenPages}:{document:CmsDocument;onOpenPages:()=>void}){
 const sections=document.pages.reduce((sum,page)=>sum+page.sections.length,0);const drafts=document.pages.filter(page=>page.status==='draft').length;
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>VISÃO GERAL</span><h1>Site / Website</h1><p>Controle editorial e visual do site institucional VISA FÁCIL.</p></div><button className="site-cms-primary" onClick={onOpenPages}>Editar páginas</button></div><div className="site-cms-kpis"><article><span>Páginas</span><strong>{document.pages.length}</strong><small>{drafts} em draft</small></article><article><span>Seções</span><strong>{sections}</strong><small>estrutura administrável</small></article><article><span>Mídias</span><strong>{document.media.length}</strong><small>biblioteca reutilizável</small></article><article><span>Última publicação</span><strong className="is-date">{formatDate(document.publishedAt)}</strong><small>conteúdo público</small></article></div><div className="site-cms-overview-grid"><section className="site-cms-card"><header><div><span>STATUS DO SITE</span><h2>Páginas</h2></div></header><div className="site-cms-page-summary">{document.pages.map(page=><button onClick={()=>go('/site-admin/pages')} key={page.id}><div><strong>{page.name}</strong><small>{page.slug}</small></div><StatusBadge status={page.status}/></button>)}</div></section><section className="site-cms-card"><header><div><span>FLUXO EDITORIAL</span><h2>Publicação segura</h2></div></header><div className="site-cms-flow"><div><b>1</b><span><strong>Editar</strong><small>Altere textos, imagens, links e ordem.</small></span></div><div><b>2</b><span><strong>Salvar draft</strong><small>Mantenha mudanças fora do site público.</small></span></div><div><b>3</b><span><strong>Pré-visualizar</strong><small>Revise o resultado final antes de publicar.</small></span></div><div><b>4</b><span><strong>Publicar</strong><small>Envie a versão aprovada ao site.</small></span></div></div></section></div></div>
}

