import { useState } from 'react';
import { cmsImageSrc } from '../public-site/content/publicContentSafety';
import { cmsMediaReferenceCount, isSafeCmsExternalUrl, isValidCmsLocale } from './cmsDocumentContract';
import type { CmsDocument, CmsMediaItem, CmsSectionInstance, CmsSettings } from './types';
import { now } from './siteCmsUtils';
import { SectionEditor } from './CmsEditors';

const SAFE_RASTER_UPLOAD_TYPES=new Set(['image/png','image/jpeg','image/gif','image/webp','image/avif']);
const SAFE_MEDIA_UPLOAD_ACCEPT='image/png,image/jpeg,image/gif,image/webp,image/avif,application/pdf,.png,.jpg,.jpeg,.gif,.webp,.avif,.pdf';

export function MediaView({document,setDocument}:{document:CmsDocument;setDocument:(doc:CmsDocument)=>void}){
 const [name,setName]=useState('');const [url,setUrl]=useState('');const [alt,setAlt]=useState('');const [message,setMessage]=useState('');
 const add=(item:Omit<CmsMediaItem,'id'|'createdAt'>)=>{const asset:CmsMediaItem={...item,id:crypto.randomUUID(),createdAt:now()};setDocument({...document,media:[asset,...document.media],updatedAt:now()});setName('');setUrl('');setAlt('');setMessage('Mídia adicionada à biblioteca.')};
 const addExternal=()=>{const normalized=url.trim();if(!isSafeCmsExternalUrl(normalized)){setMessage('Informe uma URL externa válida iniciada por http:// ou https://.');return}add({name:name||'Mídia externa',url:normalized,alt,kind:/\.(pdf)(\?|$)/i.test(normalized)?'document':'image'})};
 const upload=(file?:File)=>{if(!file)return;if(file.size>1_500_000){setMessage('Para o protótipo local, envie arquivos com até 1,5 MB. O storage definitivo removerá esse limite do navegador.');return}const image=SAFE_RASTER_UPLOAD_TYPES.has(file.type);const pdf=file.type==='application/pdf';if(!image&&!pdf){setMessage('Tipo de arquivo não suportado. Envie PNG, JPEG, GIF, WebP, AVIF ou PDF.');return}const reader=new FileReader();reader.onerror=()=>setMessage('Não foi possível ler o arquivo selecionado.');reader.onload=()=>add({name:name||file.name,url:String(reader.result),alt,kind:image?'image':'document'});reader.readAsDataURL(file)};
 const remove=(asset:CmsMediaItem)=>{const references=cmsMediaReferenceCount(document,asset.url);if(references>0){setMessage(`Não é possível remover “${asset.name}”: a mídia está em uso em ${references} ${references===1?'campo':'campos'} do site.`);return}if(!confirm(`Remover “${asset.name}” da biblioteca local?`))return;setDocument({...document,media:document.media.filter(item=>item.id!==asset.id),updatedAt:now()});setMessage('Mídia removida da biblioteca local.')};
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>MÍDIA</span><h1>Biblioteca central</h1><p>Armazene e reutilize imagens e arquivos nas seções do site.</p></div></div><section className="site-cms-media-uploader"><div className="site-cms-form-grid"><label><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Banner Canadá"/></label><label><span>Alt / descrição</span><input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Descrição para acessibilidade"/></label><label className="is-wide"><span>URL externa</span><div className="site-cms-media-url"><input type="url" value={url} onChange={e=>{setUrl(e.target.value);setMessage('')}} placeholder="https://…"/><button type="button" disabled={!url.trim()} onClick={addExternal}>Adicionar URL</button></div></label><label className="site-cms-upload is-wide"><input type="file" accept={SAFE_MEDIA_UPLOAD_ACCEPT} onChange={e=>upload(e.target.files?.[0])}/><strong>Enviar novo arquivo</strong><small>PNG, JPEG, GIF, WebP, AVIF ou PDF · no protótipo local, até 1,5 MB</small></label></div>{message&&<p className="site-cms-media-message" role="status">{message}</p>}</section><div className="site-cms-media-grid">{document.media.length===0&&<div className="site-cms-empty site-cms-empty--media"><strong>Biblioteca vazia</strong><p>Adicione uma URL ou envie um arquivo para começar.</p></div>}{document.media.map(asset=>{const references=cmsMediaReferenceCount(document,asset.url);const preview=asset.kind==='image'?cmsImageSrc(asset.url):'';return <article className="site-cms-media-card" key={asset.id}><div className="site-cms-media-thumb">{preview?<img src={preview} alt={asset.alt}/>:<span>{asset.kind==='image'?'IMG':'DOC'}</span>}</div><div className="site-cms-media-copy"><strong>{asset.name}</strong><small>{asset.alt||'Sem texto alternativo'}</small>{references>0&&<small>{references} {references===1?'referência':'referências'} no site</small>}<code>{asset.url.slice(0,58)}{asset.url.length>58?'…':''}</code></div><div className="site-cms-media-actions"><button type="button" onClick={()=>navigator.clipboard?.writeText(asset.url)}>Copiar URL</button><button type="button" className="is-danger" onClick={()=>remove(asset)}>Remover</button></div></article>})}</div></div>
}

export function GlobalsView({document,setDocument}:{document:CmsDocument;setDocument:(doc:CmsDocument)=>void}){
 const [selected,setSelected]=useState(document.globals[0]?.id||'');const section=document.globals.find(item=>item.id===selected)||document.globals[0];
 const update=(next:CmsSectionInstance)=>setDocument({...document,globals:document.globals.map(item=>item.id===next.id?next:item),updatedAt:now()});
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>CONTEÚDO GLOBAL</span><h1>Header, Footer e contatos</h1><p>Elementos compartilhados pelo site e administrados em um único lugar.</p></div></div><div className="site-cms-global-layout"><aside className="site-cms-global-nav">{document.globals.map(item=><button className={section?.id===item.id?'is-active':''} onClick={()=>setSelected(item.id)} key={item.id}><span>{item.type==='header'?'H':'F'}</span><div><strong>{item.label}</strong><small>{item.visible?'Usado globalmente':'Oculto no site'}</small></div></button>)}</aside><main>{section&&<SectionEditor section={section} document={document} onChange={update}/>}</main></div></div>
}

export function SettingsView({document,setDocument,onReset}:{document:CmsDocument;setDocument:(doc:CmsDocument)=>void;onReset:()=>void}){
 const settings=document.settings;const set=<K extends keyof CmsSettings>(key:K,value:CmsSettings[K])=>setDocument({...document,settings:{...settings,[key]:value},updatedAt:now()});
 const settingsError=!settings.siteName.trim()?'Informe o nome do site.':!isValidCmsLocale(settings.locale)?'Informe um locale BCP-47 válido, como pt-BR ou en-US.':settings.siteUrl.trim()&&!isSafeCmsExternalUrl(settings.siteUrl)?'A URL principal deve usar http:// ou https://.':settings.defaultOgImage.trim()&&!isSafeCmsExternalUrl(settings.defaultOgImage)?'A OG Image padrão deve usar uma URL absoluta http:// ou https://.':'';
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>CONFIGURAÇÕES</span><h1>Configurações do site</h1><p>Parâmetros globais que não pertencem a uma seção específica.</p></div></div><section className="site-cms-card site-cms-settings-card"><header><div><span>GERAL</span><h2>Identidade e URL</h2></div></header><div className="site-cms-form-grid site-cms-settings-body"><label><span>Nome do site</span><input value={settings.siteName} onChange={e=>set('siteName',e.target.value)}/></label><label><span>Organização</span><input value={settings.organizationName} onChange={e=>set('organizationName',e.target.value)}/></label><label><span>URL principal</span><input type="url" value={settings.siteUrl} onChange={e=>set('siteUrl',e.target.value)} placeholder="https://visafacil.com.br"/></label><label><span>Locale</span><input value={settings.locale} onChange={e=>set('locale',e.target.value)} placeholder="pt-BR"/></label><label className="is-wide"><span>OG Image padrão</span><input type="url" value={settings.defaultOgImage} onChange={e=>set('defaultOgImage',e.target.value)} placeholder="https://…"/></label></div>{settingsError&&<p className="site-cms-form-error" role="alert">{settingsError}</p>}</section><section className="site-cms-card site-cms-danger-card"><header><div><span>MANUTENÇÃO</span><h2>Reset do CMS local</h2><p>Restaura rascunho e conteúdo publicado para a versão inicial do código.</p></div><button onClick={()=>{if(confirm('Restaurar todo o conteúdo local do CMS?'))onReset()}}>Restaurar conteúdo inicial</button></header></section></div>
}
