import { useState } from 'react';
import { resetCms } from './siteStore';
import type { CmsDocument, CmsMediaItem, CmsSectionInstance, CmsSettings } from './types';
import { now } from './siteCmsUtils';
import { SectionEditor } from './CmsEditors';

export function MediaView({document,setDocument}:{document:CmsDocument;setDocument:(doc:CmsDocument)=>void}){
 const [name,setName]=useState('');const [url,setUrl]=useState('');const [alt,setAlt]=useState('');const [message,setMessage]=useState('');
 const add=(item:Omit<CmsMediaItem,'id'|'createdAt'>)=>{const asset:CmsMediaItem={...item,id:crypto.randomUUID(),createdAt:now()};setDocument({...document,media:[asset,...document.media],updatedAt:now()});setName('');setUrl('');setAlt('');setMessage('Mídia adicionada à biblioteca.')};
 const upload=(file?:File)=>{if(!file)return;if(file.size>1_500_000){setMessage('Para o protótipo local, envie imagens com até 1,5 MB. O storage definitivo removerá esse limite do navegador.');return}const reader=new FileReader();reader.onload=()=>add({name:name||file.name,url:String(reader.result),alt,kind:file.type.startsWith('image/')?'image':'document'});reader.readAsDataURL(file)};
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>MÍDIA</span><h1>Biblioteca central</h1><p>Armazene e reutilize imagens e arquivos nas seções do site.</p></div></div><section className="site-cms-media-uploader"><div className="site-cms-form-grid"><label><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Banner Canadá"/></label><label><span>Alt / descrição</span><input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Descrição para acessibilidade"/></label><label className="is-wide"><span>URL externa</span><div className="site-cms-media-url"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/><button onClick={()=>url&&add({name:name||'Mídia externa',url,alt,kind:/\.(pdf|doc|docx)(\?|$)/i.test(url)?'document':'image'})}>Adicionar URL</button></div></label><label className="site-cms-upload is-wide"><input type="file" accept="image/*,.pdf" onChange={e=>upload(e.target.files?.[0])}/><strong>Enviar novo arquivo</strong><small>Imagem ou PDF · no protótipo local, até 1,5 MB</small></label></div>{message&&<p className="site-cms-media-message">{message}</p>}</section><div className="site-cms-media-grid">{document.media.length===0&&<div className="site-cms-empty site-cms-empty--media"><strong>Biblioteca vazia</strong><p>Adicione uma URL ou envie um arquivo para começar.</p></div>}{document.media.map(asset=><article className="site-cms-media-card" key={asset.id}><div className="site-cms-media-thumb">{asset.kind==='image'?<img src={asset.url} alt={asset.alt}/>:<span>DOC</span>}</div><div className="site-cms-media-copy"><strong>{asset.name}</strong><small>{asset.alt||'Sem texto alternativo'}</small><code>{asset.url.slice(0,58)}{asset.url.length>58?'…':''}</code></div><div className="site-cms-media-actions"><button onClick={()=>navigator.clipboard?.writeText(asset.url)}>Copiar URL</button><button className="is-danger" onClick={()=>setDocument({...document,media:document.media.filter(item=>item.id!==asset.id),updatedAt:now()})}>Remover</button></div></article>)}</div></div>
}

export function GlobalsView({document,setDocument}:{document:CmsDocument;setDocument:(doc:CmsDocument)=>void}){
 const [selected,setSelected]=useState(document.globals[0]?.id||'');const section=document.globals.find(item=>item.id===selected)||document.globals[0];
 const update=(next:CmsSectionInstance)=>setDocument({...document,globals:document.globals.map(item=>item.id===next.id?next:item),updatedAt:now()});
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>CONTEÚDO GLOBAL</span><h1>Header, Footer e contatos</h1><p>Elementos compartilhados pelo site e administrados em um único lugar.</p></div></div><div className="site-cms-global-layout"><aside className="site-cms-global-nav">{document.globals.map(item=><button className={section?.id===item.id?'is-active':''} onClick={()=>setSelected(item.id)} key={item.id}><span>{item.type==='header'?'H':'F'}</span><div><strong>{item.label}</strong><small>Usado globalmente</small></div></button>)}</aside><main>{section&&<SectionEditor section={section} document={document} onChange={update}/>}</main></div></div>
}

export function SettingsView({document,setDocument}:{document:CmsDocument;setDocument:(doc:CmsDocument)=>void}){
 const settings=document.settings;const set=<K extends keyof CmsSettings>(key:K,value:CmsSettings[K])=>setDocument({...document,settings:{...settings,[key]:value},updatedAt:now()});
 return <div className="site-cms-view"><div className="site-cms-page-title"><div><span>CONFIGURAÇÕES</span><h1>Configurações do site</h1><p>Parâmetros globais que não pertencem a uma seção específica.</p></div></div><section className="site-cms-card site-cms-settings-card"><header><div><span>GERAL</span><h2>Identidade e URL</h2></div></header><div className="site-cms-form-grid site-cms-settings-body"><label><span>Nome do site</span><input value={settings.siteName} onChange={e=>set('siteName',e.target.value)}/></label><label><span>Organização</span><input value={settings.organizationName} onChange={e=>set('organizationName',e.target.value)}/></label><label><span>URL principal</span><input value={settings.siteUrl} onChange={e=>set('siteUrl',e.target.value)} placeholder="https://visafacil.com.br"/></label><label><span>Locale</span><input value={settings.locale} onChange={e=>set('locale',e.target.value)}/></label><label className="is-wide"><span>OG Image padrão</span><input value={settings.defaultOgImage} onChange={e=>set('defaultOgImage',e.target.value)}/></label></div></section><section className="site-cms-card site-cms-danger-card"><header><div><span>MANUTENÇÃO</span><h2>Reset do CMS local</h2><p>Restaura rascunho e conteúdo publicado para a versão inicial do código.</p></div><button onClick={()=>{if(confirm('Restaurar todo o conteúdo local do CMS?'))setDocument(resetCms())}}>Restaurar conteúdo inicial</button></header></section></div>
}
