import type { CmsSectionDefinition } from './types';
import { cardFields, image, navFields, repeater, select, text, textarea, titleDescriptionFields, url } from './siteSchemaFields';

export const DEFINITIONS:Record<string,CmsSectionDefinition>={
hero:{type:'hero',label:'Hero',description:'Headline principal, benefícios, CTAs, banners e faixa de confiança.',category:'page',fields:[
    text('headlineLine1','Título · linha 1','O caminho mais fácil'),text('headlineLine2','Título · linha 2','para o seu visto'),text('headlineAccent','Título · destaque','começa aqui.'),
    repeater('trustItems','Diferenciais rápidos',[{text:'Atendimento online'},{text:'Suporte em português'},{text:'Processo personalizado'}],[{id:'text',label:'Texto',type:'text'}]),
    repeater('miniBenefits','Mini benefícios',[{icon:'★',text:'Atendimento nacional'},{icon:'◎',text:'Estratégia individual'},{icon:'↗',text:'Jornada conectada'},{icon:'◯',text:'Comunicação clara'}],[{id:'icon',label:'Ícone',type:'text'},{id:'text',label:'Texto',type:'text'}]),
    text('primaryCtaLabel','Botão principal','Analisar meu perfil'),url('primaryCtaUrl','Link do botão principal','#diagnostico'),select('primaryCtaTarget','Abrir botão principal em','_self',['_self','_blank']),text('secondaryCtaLabel','Botão secundário','Conhecer os serviços'),url('secondaryCtaUrl','Link do botão secundário','#servicos'),select('secondaryCtaTarget','Abrir botão secundário em','_self',['_self','_blank']),
    repeater('slides','Banners',[{image:'',alt:'Estátua da Liberdade, skyline de Nova York e bandeira dos Estados Unidos'},{image:'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1800&q=90',alt:'Nova York, Estados Unidos'},{image:'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1800&q=90',alt:'Toronto, Canadá'}],[{id:'image',label:'Imagem',type:'image'},{id:'alt',label:'Texto alternativo',type:'text'}]),
    repeater('confidenceItems','Faixa de confiança',[{title:'Atendimento nacional',description:'Onde você estiver'},{title:'Estratégia individual',description:'Sem pacote genérico'},{title:'Jornada conectada',description:'Do visto à próxima etapa'},{title:'Comunicação clara',description:'Orientação em português'}],titleDescriptionFields)
  ]},
'services-intro':{type:'services-intro',label:'Introdução de Serviços',description:'Texto de abertura que apresenta a proposta da assessoria.',category:'page',fields:[text('kicker','Kicker','O que fazemos'),text('title','Título','Uma assessoria completa para transformar planos em possibilidades reais.'),textarea('description','Descrição','Um processo de visto envolve perfil, formulários, documentos, prazos e entrevista. Por isso, cada serviço é organizado de forma personalizada, com atenção aos detalhes e acompanhamento próximo.'),text('ctaLabel','Texto do link','Descobrir por onde começar'),url('ctaUrl','Link','#diagnostico'),select('ctaTarget','Abrir link em','_self',['_self','_blank'])]},
services:{type:'services',label:'Serviços',description:'Cards de vistos e serviços complementares atualmente exibidos no site.',category:'page',fields:[
    repeater('cards','Cards de serviços',[
      {anchor:'eua',label:'Estados Unidos',title:'Visto americano',description:'Análise de perfil, preenchimento do DS-160, organização documental, agendamento e preparação individual para entrevista.',image:'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1200&q=86',alt:'Nova York, Estados Unidos',bullets:'Turismo e negócios\nRenovação de visto\nReaplicação após negativa',ctaLabel:'Ver como funciona',ctaUrl:'#diagnostico',ctaTarget:'_self'},
      {anchor:'canada',label:'Canadá',title:'Visto canadense',description:'Orientação para formulários, documentos, biometria e eventuais solicitações adicionais da autoridade canadense.',image:'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=900&q=86',alt:'Toronto, Canadá',bullets:'',ctaLabel:'Analisar meu caso',ctaUrl:'#diagnostico',ctaTarget:'_self'},
      {anchor:'australia',label:'Austrália',title:'Visto australiano',description:'Planejamento da solicitação, revisão das evidências e acompanhamento documental conforme a categoria aplicável.',image:'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=900&q=86',alt:'Sydney, Austrália',bullets:'',ctaLabel:'Analisar meu caso',ctaUrl:'#diagnostico',ctaTarget:'_self'},
      {anchor:'europa-schengen',label:'Europa',title:'Vistos e autorizações',description:'Suporte para destinos e categorias que exigem visto, autorização, seguro ou comprovação documental específica.',image:'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=900&q=86',alt:'Paris, França',bullets:'',ctaLabel:'Analisar meu destino',ctaUrl:'#diagnostico',ctaTarget:'_self'}
    ],cardFields),
    repeater('supportCards','Serviços complementares',[{icon:'↻',title:'Renovação de visto',description:'Atualização do processo conforme histórico, perfil e regras vigentes.'},{icon:'◎',title:'Preparação para entrevista',description:'Simulação individual, coerência e comunicação clara — sem respostas decoradas.'},{icon:'✓',title:'Revisão de formulários',description:'Conferência técnica para reduzir erros, omissões e inconsistências.'}],[{id:'icon',label:'Ícone',type:'text'},...titleDescriptionFields])
  ]}
};
