import type { CmsSectionDefinition } from './types';
import { cardFields, image, navFields, repeater, select, text, textarea, titleDescriptionFields, url } from './siteSchemaFields';

export const DEFINITIONS:Record<string,CmsSectionDefinition>={
header:{type:'header',label:'Header / Navegação',description:'Barra de anúncio, marca, navegação principal e CTA do cabeçalho.',category:'global',fields:[
    text('announcementText','Texto do anúncio','Atendimento online para todo o Brasil'),text('announcementCtaLabel','CTA do anúncio','Faça uma análise inicial gratuita'),url('announcementCtaUrl','Link do anúncio','#diagnostico'),select('announcementCtaTarget','Abrir CTA do anúncio em','_self',['_self','_blank']),text('brandName','Nome da marca','VISA FÁCIL'),text('brandTagline','Tagline','seu visto, sem complicação'),image('logoImage','Logo personalizada','', 'Deixe vazio para usar a marca vetorial atual.'),
    repeater('primaryNav','Navegação principal',[{label:'EUA',url:'#eua',target:'_self'},{label:'Canadá',url:'#canada',target:'_self'},{label:'Como Funciona',url:'#processo',target:'_self'},{label:'Dúvidas',url:'#duvidas',target:'_self'}],navFields),
    repeater('visaMenu','Itens do menu Vistos',[{label:'Austrália',url:'#australia',target:'_self',description:'Planejamento e evidências'},{label:'Europa e Schengen',url:'#europa-schengen',target:'_self',description:'Autorizações e requisitos'}],[...navFields,{id:'description',label:'Descrição',type:'text'}]),
    text('headerCtaLabel','Texto do CTA','Analisar meu perfil'),url('headerCtaUrl','Link do CTA','#diagnostico'),select('headerCtaTarget','Abrir CTA em','_self',['_self','_blank'])
  ]},
footer:{type:'footer',label:'Footer',description:'Marca, links, redes sociais, contatos, copyright e CTA flutuante.',category:'global',fields:[text('brandName','Nome da marca','VISA FÁCIL'),text('brandTagline','Tagline','seu visto, sem complicação'),image('logoImage','Logo personalizada','', 'Deixe vazio para usar a marca vetorial atual.'),textarea('description','Descrição','Assessoria especializada para vistos internacionais, com atendimento em português, processo personalizado e orientação clara em cada etapa.'),repeater('socialLinks','Redes sociais',[{label:'Instagram',shortLabel:'ig',url:'#',target:'_blank'},{label:'Facebook',shortLabel:'f',url:'#',target:'_blank'},{label:'TikTok',shortLabel:'tk',url:'#',target:'_blank'}],[{id:'label',label:'Rede',type:'text'},{id:'shortLabel',label:'Abreviação',type:'text'},{id:'url',label:'URL',type:'url'},{id:'target',label:'Abrir em',type:'select',options:['_self','_blank']}]),repeater('serviceLinks','Links de serviços',[{label:'Visto americano',url:'#eua',target:'_self'},{label:'Visto canadense',url:'#canada',target:'_self'},{label:'Visto australiano',url:'#australia',target:'_self'},{label:'Europa e Schengen',url:'#europa-schengen',target:'_self'}],navFields),repeater('infoLinks','Links institucionais',[{label:'Como funciona',url:'#processo',target:'_self'},{label:'Dúvidas frequentes',url:'#duvidas',target:'_self'},{label:'Contato',url:'#diagnostico',target:'_self'},{label:'Política de privacidade',url:'#',target:'_self'},{label:'Termos de uso',url:'#',target:'_self'}],navFields),text('whatsapp','WhatsApp','preencher'),url('whatsappUrl','Link do WhatsApp',''),select('whatsappTarget','Abrir WhatsApp em','_blank',['_self','_blank']),text('email','E-mail','preencher'),text('serviceDays','Dias de atendimento','Segunda a sexta'),text('serviceHours','Horário','preencher'),text('copyright','Copyright','© 2026 VISA FÁCIL. Todos os direitos reservados.'),textarea('disclaimer','Aviso legal','Não somos órgão consular e não garantimos decisões de autoridades públicas.'),text('floatingCtaLabel','CTA flutuante','Falar com a equipe'),url('floatingCtaUrl','Link do CTA flutuante','#diagnostico'),select('floatingCtaTarget','Abrir CTA flutuante em','_self',['_self','_blank'])]}
};
