import { useState } from 'react';
import './finance.css';

type Rule={id:string;contains:string;category:string;type:'Receita'|'Despesa';active:boolean};
type Mode='create'|'view'|'edit';
const CATEGORIES=['Assessoria','Renovação','Taxas consulares','Serviços terceiros','Marketing','Outros'];
const INITIAL:Rule[]=[{id:'rule-1',contains:'META ADS',category:'Marketing',type:'Despesa',active:true},{id:'rule-2',contains:'CONSULADO',category:'Taxas consulares',type:'Despesa',active:true},{id:'rule-3',contains:'VISA FACIL',category:'Assessoria',type:'Receita',active:true}];
const NAV=[['Dashboard','/crm'],['CRM','/crm/relacionamento'],['Atendimentos','/crm/atendimentos'],['Tarefas','/crm/tarefas'],['Agenda','/crm/agenda'],['Financeiro','/crm/financeiro'],['Relatórios','/crm/relatorios'],['Configurações','/crm/configuracoes']];
function base(){return import.meta.env.BASE_URL.replace(/\/$/,'')}
function href(p:string){return `${base()}${p}`}
function Shell({children}:{children:React.ReactNode}){return <div className="crm-shell finance-shell"><aside className="crm-sidebar"><a className="crm-brand" href={href('/crm')}><span className="crm-brand-mark"><i/><b/></span><span><strong>VISA FÁCIL</strong><small>CRM · Relacionamento</small></span></a><div className="crm-sidebar-accent"><i/><i/><i/></div><span className="crm-sidebar-label">OPERAÇÃO</span><nav>{NAV.map(([l,p])=><a key={p} className={p==='/crm/financeiro'?'is-active':''} href={href(p)}>{l}</a>)}</nav></aside><div className="crm-workspace">{children}</div></div>}
function RuleModal({mode,item,onClose,onSave}:{mode:Mode;item?:Rule;onClose:()=>void;onSave:(v:Omit<Rule,'id'>)=>void}){const [contains,setContains]=useState(item?.contains??'');const [category,setCategory]=useState(item?.category??'Assessoria');const [type,setType]=useState<'Receita'|'Despesa'>(item?.type??'Receita');const [active,setActive]=useState(item?.active??true);if(mode==='view'&&item)return <div className="finance-modal-backdrop"><div className="finance-view-modal"><header><div><span>REGRA FINANCEIRA</span><h2>{item.contains}</h2><p>Visualização do registro</p></div><button onClick={onClose}>×</button></header><section className="finance-view-body"><div className="finance-view-grid"><div><span>Descrição contém</span><strong>{item.contains}</strong></div><div><span>Categoria</span><strong>{item.category}</strong></div><div><span>Tipo</span><strong>{item.type}</strong></div><div><span>Status</span><strong>{item.active?'Ativa':'Inativa'}</strong></div></div></section><footer><button className="crm-btn-secondary" onClick={onClose}>Fechar</button></footer></div></div>;return <div className="finance-modal-backdrop"><div className="finance-form-modal"><header><div><span>{mode==='create'?'CRIAR REGRA':'EDITAR REGRA'}</span><h2>{mode==='create'?'Nova regra financeira':'Editar regra financeira'}</h2></div><button onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();if(contains.trim())onSave({contains:contains.trim(),category,type,active})}}><div className="finance-form-grid"><label><span>Descrição contém</span><input value={contains} onChange={e=>setContains(e.target.value)} required/></label><label><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Tipo</span><select value={type} onChange={e=>setType(e.target.value as any)}><option>Receita</option><option>Despesa</option></select></label><label><span>Status</span><select value={active?'Ativa':'Inativa'} onChange={e=>setActive(e.target.value==='Ativa')}><option>Ativa</option><option>Inativa</option></select></label></div><footer><button type="button" className="crm-btn-secondary" onClick={onClose}>Cancelar</button><button className="crm-btn-primary">Salvar</button></footer></form></div></div>}
export function FinancialRulesApp(){const [items,setItems]=useState(INITIAL);const [modal,setModal]=useState<{mode:Mode;item?:Rule}>();const [menu,setMenu]=useState<string>();const save=(v:Omit<Rule,'id'>)=>{if(modal?.item)setItems(a=>a.map(x=>x.id===modal.item!.id?{...x,...v}:x));else setItems(a=>[{id:crypto.randomUUID(),...v},...a]);setModal(undefined)};const del=(x:Rule)=>{if(confirm(`Excluir a regra “${x.contains}”?`))setItems(a=>a.filter(i=>i.id!==x.id))};return <Shell><header className="crm-topbar"><div><small>VISA FÁCIL · CRM</small><h1>Regras Financeiras</h1><p>Gerencie regras automáticas de classificação financeira.</p></div><div className="crm-topbar-actions finance-header-actions"><a className="finance-header-nav-button" href={href('/crm/financeiro')}>← Financeiro</a><button className="crm-topbar-primary" onClick={()=>setModal({mode:'create'})}>+ Criar</button></div></header><main className="finance-content"><section className="finance-config-card"><div className="finance-rules-list finance-rules-list--actions"><div className="finance-rule-head"><span>Descrição contém</span><span>Categoria</span><span>Tipo</span><span>Status</span><span>Ações</span></div>{items.map(x=><article key={x.id}><div><span>Descrição contém</span><strong>{x.contains}</strong></div><div><span>Categoria</span><strong>{x.category}</strong></div><div><span>Tipo</span><strong>{x.type}</strong></div><b className={x.active?'is-active':''}>{x.active?'Ativa':'Inativa'}</b><div className="finance-row-actions"><button className="finance-actions-trigger" onClick={()=>setMenu(menu===x.id?undefined:x.id)}>⋮</button>{menu===x.id&&<div className="finance-actions-menu"><button onClick={()=>setModal({mode:'view',item:x})}>Ver</button><button onClick={()=>setModal({mode:'edit',item:x})}>Editar</button><button className="is-danger" onClick={()=>del(x)}>Excluir</button></div>}</div></article>)}</div></section></main>{modal&&<RuleModal mode={modal.mode} item={modal.item} onClose={()=>setModal(undefined)} onSave={save}/>}</Shell>}
