import { useState } from 'react';
import './finance-config.css';
import { getFinanceCategories, getFinanceRules, saveFinanceRules, type FinanceRule } from './financeConfigStore';
import type { FinanceType } from './types';

type Mode='create'|'view'|'edit';
function base(){return import.meta.env.BASE_URL.replace(/\/$/,'')}
function href(path:string){return `${base()}${path}`||path}

function RuleModal({mode,item,onClose,onSave,existing}:{mode:Mode;item?:FinanceRule;onClose:()=>void;onSave:(value:Omit<FinanceRule,'id'>)=>void;existing:FinanceRule[]}){
 const [contains,setContains]=useState(item?.contains??'');
 const [type,setType]=useState<FinanceType>(item?.type??'Receita');
 const categories=getFinanceCategories().filter(category=>category.active&&category.type===type);
 const [category,setCategory]=useState(item?.category??categories[0]?.name??'');
 const [active,setActive]=useState(item?.active??true);
 const duplicate=existing.some(rule=>rule.id!==item?.id&&rule.type===type&&rule.contains.trim().toLocaleUpperCase('pt-BR')===contains.trim().toLocaleUpperCase('pt-BR'));
 const changeType=(next:FinanceType)=>{setType(next);const first=getFinanceCategories().find(candidate=>candidate.active&&candidate.type===next);setCategory(first?.name??'')};
 if(mode==='view'&&item)return <div className="finance-modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><div className="finance-view-modal"><header><div><span>REGRA FINANCEIRA</span><h2>{item.contains}</h2><p>Classificação aplicada às importações OFX nesta sessão</p></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><section className="finance-view-body"><div className="finance-view-grid"><div><span>Descrição contém</span><strong>{item.contains}</strong></div><div><span>Categoria</span><strong>{item.category}</strong></div><div><span>Tipo</span><strong>{item.type}</strong></div><div><span>Status</span><strong>{item.active?'Ativa':'Inativa'}</strong></div></div></section><footer><button className="crm-btn-secondary" type="button" onClick={onClose}>Fechar</button></footer></div></div>;
 return <div className="finance-modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><div className="finance-form-modal"><header><div><span>{mode==='create'?'CRIAR REGRA':'EDITAR REGRA'}</span><h2>{mode==='create'?'Nova regra financeira':'Editar regra financeira'}</h2></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><form onSubmit={event=>{event.preventDefault();const clean=contains.trim();if(clean&&category&&!duplicate)onSave({contains:clean,category,type,active})}}><div className="finance-form-grid"><label><span>Descrição contém</span><input value={contains} onChange={event=>setContains(event.target.value)} required/></label><label><span>Tipo</span><select value={type} onChange={event=>changeType(event.target.value as FinanceType)}><option>Receita</option><option>Despesa</option></select></label><label><span>Categoria</span><select value={category} onChange={event=>setCategory(event.target.value)} disabled={!categories.length}>{categories.length?categories.map(value=><option key={value.id} value={value.name}>{value.name}</option>):<option value="">Nenhuma categoria ativa para este tipo</option>}</select></label><label><span>Status</span><select value={active?'Ativa':'Inativa'} onChange={event=>setActive(event.target.value==='Ativa')}><option>Ativa</option><option>Inativa</option></select></label></div>{duplicate&&<p className="finance-config-note" role="alert">Já existe uma regra para esse texto e tipo.</p>}<footer><button type="button" className="crm-btn-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="crm-btn-primary" disabled={!contains.trim()||!category||duplicate}>Salvar</button></footer></form></div></div>;
}

export function FinancialRulesApp(){
 const [items,setItems]=useState<FinanceRule[]>(()=>getFinanceRules());
 const [modal,setModal]=useState<{mode:Mode;item?:FinanceRule}>();
 const [menu,setMenu]=useState<string>();
 const commit=(next:FinanceRule[])=>{setItems(next);saveFinanceRules(next)};
 const save=(value:Omit<FinanceRule,'id'>)=>{const next=modal?.item?items.map(item=>item.id===modal.item!.id?{...item,...value}:item):[{id:crypto.randomUUID(),...value},...items];commit(next);setModal(undefined)};
 const remove=(item:FinanceRule)=>{setMenu(undefined);if(window.confirm(`Excluir a regra “${item.contains}”?`))commit(items.filter(candidate=>candidate.id!==item.id))};
 return <div className="crm-shell finance-shell"><div className="crm-workspace"><header className="crm-topbar"><div><small>VISA FÁCIL · CRM · FINANCEIRO</small><h1>Regras Financeiras</h1><p>Classifique automaticamente movimentações OFX pela descrição.</p></div><div className="crm-topbar-actions finance-header-actions"><a className="finance-header-nav-button" href={href('/crm/financeiro')}>← Transações</a><button className="crm-topbar-primary" type="button" onClick={()=>setModal({mode:'create'})}>+ Criar</button></div></header><main className="finance-content"><section className="finance-config-card"><div className="finance-rules-list finance-rules-list--actions"><div className="finance-rule-head"><span>Descrição contém</span><span>Categoria</span><span>Tipo</span><span>Status</span><span>Ações</span></div>{items.map(item=><article key={item.id}><div><span>Descrição contém</span><strong>{item.contains}</strong></div><div><span>Categoria</span><strong>{item.category}</strong></div><div><span>Tipo</span><strong>{item.type}</strong></div><b className={item.active?'is-active':''}>{item.active?'Ativa':'Inativa'}</b><div className="finance-row-actions"><button className="finance-actions-trigger" type="button" aria-label={`Ações da regra ${item.contains}`} onClick={()=>setMenu(menu===item.id?undefined:item.id)}>⋮</button>{menu===item.id&&<div className="finance-actions-menu"><button type="button" onClick={()=>{setMenu(undefined);setModal({mode:'view',item})}}>Ver</button><button type="button" onClick={()=>{setMenu(undefined);setModal({mode:'edit',item})}}>Editar</button><button type="button" className="is-danger" onClick={()=>remove(item)}>Excluir</button></div>}</div></article>)}</div><p className="finance-config-note">As regras são armazenadas somente na sessão do navegador e aplicadas às novas importações OFX. Não existe persistência server-side neste repositório.</p></section></main>{modal&&<RuleModal mode={modal.mode} item={modal.item} existing={items} onClose={()=>setModal(undefined)} onSave={save}/>}</div></div>;
}

export default FinancialRulesApp;
