import { useState } from 'react';
import './finance.css';

type RuleType='Receita'|'Despesa';
type Rule={id:string;contains:string;category:string;type:RuleType;active:boolean};
type Mode='create'|'view'|'edit';
const CATEGORIES=['Assessoria','Renovação','Taxas consulares','Serviços terceiros','Marketing','Outros'];
const INITIAL:Rule[]=[{id:'rule-1',contains:'META ADS',category:'Marketing',type:'Despesa',active:true},{id:'rule-2',contains:'CONSULADO',category:'Taxas consulares',type:'Despesa',active:true},{id:'rule-3',contains:'VISA FACIL',category:'Assessoria',type:'Receita',active:true}];
function base(){return import.meta.env.BASE_URL.replace(/\/$/,'')}
function href(path:string){return `${base()}${path}`||path}

function RuleModal({mode,item,onClose,onSave}:{mode:Mode;item?:Rule;onClose:()=>void;onSave:(value:Omit<Rule,'id'>)=>void}){
 const [contains,setContains]=useState(item?.contains??'');
 const [category,setCategory]=useState(item?.category??'Assessoria');
 const [type,setType]=useState<RuleType>(item?.type??'Receita');
 const [active,setActive]=useState(item?.active??true);
 if(mode==='view'&&item)return <div className="finance-modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><div className="finance-view-modal"><header><div><span>REGRA FINANCEIRA</span><h2>{item.contains}</h2><p>Visualização do registro</p></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><section className="finance-view-body"><div className="finance-view-grid"><div><span>Descrição contém</span><strong>{item.contains}</strong></div><div><span>Categoria</span><strong>{item.category}</strong></div><div><span>Tipo</span><strong>{item.type}</strong></div><div><span>Status</span><strong>{item.active?'Ativa':'Inativa'}</strong></div></div></section><footer><button className="crm-btn-secondary" type="button" onClick={onClose}>Fechar</button></footer></div></div>;
 return <div className="finance-modal-backdrop" onMouseDown={event=>event.currentTarget===event.target&&onClose()}><div className="finance-form-modal"><header><div><span>{mode==='create'?'CRIAR REGRA':'EDITAR REGRA'}</span><h2>{mode==='create'?'Nova regra financeira':'Editar regra financeira'}</h2></div><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><form onSubmit={event=>{event.preventDefault();if(contains.trim())onSave({contains:contains.trim(),category,type,active})}}><div className="finance-form-grid"><label><span>Descrição contém</span><input value={contains} onChange={event=>setContains(event.target.value)} required/></label><label><span>Categoria</span><select value={category} onChange={event=>setCategory(event.target.value)}>{CATEGORIES.map(value=><option key={value}>{value}</option>)}</select></label><label><span>Tipo</span><select value={type} onChange={event=>setType(event.target.value as RuleType)}><option>Receita</option><option>Despesa</option></select></label><label><span>Status</span><select value={active?'Ativa':'Inativa'} onChange={event=>setActive(event.target.value==='Ativa')}><option>Ativa</option><option>Inativa</option></select></label></div><footer><button type="button" className="crm-btn-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="crm-btn-primary">Salvar</button></footer></form></div></div>;
}

export function FinancialRulesApp(){
 const [items,setItems]=useState(INITIAL);
 const [modal,setModal]=useState<{mode:Mode;item?:Rule}>();
 const [menu,setMenu]=useState<string>();
 const save=(value:Omit<Rule,'id'>)=>{if(modal?.item)setItems(current=>current.map(item=>item.id===modal.item!.id?{...item,...value}:item));else setItems(current=>[{id:crypto.randomUUID(),...value},...current]);setModal(undefined)};
 const remove=(item:Rule)=>{setMenu(undefined);if(window.confirm(`Excluir a regra “${item.contains}”?`))setItems(current=>current.filter(candidate=>candidate.id!==item.id))};
 return <div className="crm-shell finance-shell"><div className="crm-workspace"><header className="crm-topbar"><div><small>VISA FÁCIL · CRM · FINANCEIRO</small><h1>Regras Financeiras</h1><p>Gerencie regras de classificação usadas pela futura importação financeira.</p></div><div className="crm-topbar-actions finance-header-actions"><a className="finance-header-nav-button" href={href('/crm/financeiro')}>← Transações</a><button className="crm-topbar-primary" type="button" onClick={()=>setModal({mode:'create'})}>+ Criar</button></div></header><main className="finance-content"><section className="finance-config-card"><div className="finance-rules-list finance-rules-list--actions"><div className="finance-rule-head"><span>Descrição contém</span><span>Categoria</span><span>Tipo</span><span>Status</span><span>Ações</span></div>{items.map(item=><article key={item.id}><div><span>Descrição contém</span><strong>{item.contains}</strong></div><div><span>Categoria</span><strong>{item.category}</strong></div><div><span>Tipo</span><strong>{item.type}</strong></div><b className={item.active?'is-active':''}>{item.active?'Ativa':'Inativa'}</b><div className="finance-row-actions"><button className="finance-actions-trigger" type="button" aria-label={`Ações da regra ${item.contains}`} onClick={()=>setMenu(menu===item.id?undefined:item.id)}>⋮</button>{menu===item.id&&<div className="finance-actions-menu"><button type="button" onClick={()=>setModal({mode:'view',item})}>Ver</button><button type="button" onClick={()=>setModal({mode:'edit',item})}>Editar</button><button type="button" className="is-danger" onClick={()=>remove(item)}>Excluir</button></div>}</div></article>)}</div><p className="finance-config-note">Estas regras ainda não executam importação OFX porque não existe parser/persistência bancária neste repositório.</p></section></main>{modal&&<RuleModal mode={modal.mode} item={modal.item} onClose={()=>setModal(undefined)} onSave={save}/>}</div></div>;
}
