import { useMemo, useState } from 'react';
import './finance-accounting.css';
import { getFinanceInitialRecords, type FinanceRecord } from './mocks/financeMockProvider';

function money(value:number){return value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}

export function FinancePLApp(){
 const records=useMemo<FinanceRecord[]>(()=>getFinanceInitialRecords(),[]);
 const [start,setStart]=useState('');const [end,setEnd]=useState('');const [query,setQuery]=useState('');const [kind,setKind]=useState('Todos');
 const filtered=useMemo(()=>records.filter(r=>{const q=query.trim().toLowerCase();return(!start||!r.date||r.date>=start)&&(!end||!r.date||r.date<=end)&&(kind==='Todos'||r.type===kind)&&(!q||`${r.category} ${r.description} ${r.relatedName}`.toLowerCase().includes(q))}),[records,start,end,query,kind]);
 const revenue=filtered.filter(r=>r.type==='Receita').reduce((s,r)=>s+r.amount,0);const expense=filtered.filter(r=>r.type==='Despesa').reduce((s,r)=>s+r.amount,0);const net=revenue-expense;const margin=revenue>0?net/revenue*100:0;
 const categories=useMemo(()=>{const map=new Map<string,{category:string,revenue:number,expense:number}>();filtered.forEach(r=>{const cur=map.get(r.category)||{category:r.category,revenue:0,expense:0};if(r.type==='Receita')cur.revenue+=r.amount;else cur.expense+=r.amount;map.set(r.category,cur)});return [...map.values()].map(x=>({...x,result:x.revenue-x.expense,share:revenue>0?((x.revenue-x.expense)/revenue)*100:0})).sort((a,b)=>b.result-a.result)},[filtered,revenue]);
 return <div className="crm-shell finance-accounting-shell"><div className="crm-workspace"><header className="crm-topbar"><div><small>VISA FÁCIL · CRM · FINANCEIRO</small><h1>P&amp;L</h1><p>Receitas, despesas, lucro líquido e margem por categoria financeira.</p></div><div className="crm-topbar-actions"><button aria-label="Alertas"/><button className="crm-user"><span>VF</span><div><strong>Administrador</strong><small>Protótipo frontend</small></div></button></div></header><main className="finance-content"><section className="finance-pl-filters"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/><input className="finance-pl-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar categoria, descrição ou contato..."/><select value={kind} onChange={e=>setKind(e.target.value)}><option>Todos</option><option>Receita</option><option>Despesa</option></select></section><section className="finance-pl-kpis"><article><small>Receita total</small><strong>{money(revenue)}</strong><span>Receitas no período selecionado</span></article><article><small>Despesas totais</small><strong>{money(expense)}</strong><span>Despesas no período selecionado</span></article><article><small>Lucro líquido</small><strong className={net<0?'is-negative':''}>{net<0?'-':''}{money(Math.abs(net))}</strong><span>Receitas menos despesas</span></article><article><small>Margem líquida</small><strong>{margin.toFixed(1)}%</strong><span>Lucro líquido / receita</span></article></section><section className="finance-accounting-table finance-pl-table"><div className="finance-accounting-head finance-pl-head"><span>Categoria</span><span>Receitas</span><span>Despesas</span><span>Resultado</span><span>Margem</span></div>{categories.length?categories.map(r=><div className="finance-accounting-row finance-pl-row" key={r.category}><strong>{r.category}</strong><span>{r.revenue?money(r.revenue):'—'}</span><span>{r.expense?`- ${money(r.expense)}`:'—'}</span><strong className={r.result<0?'is-negative':''}>{r.result<0?'- ':'+ '}{money(Math.abs(r.result))}</strong><span>{r.share.toFixed(1)}%</span></div>):<div className="finance-empty">Nenhum dado de P&amp;L para os filtros atuais.</div>}<div className="finance-pl-total"><strong>Total</strong><strong>{money(revenue)}</strong><strong>- {money(expense)}</strong><strong>{net<0?'- ':'+ '}{money(Math.abs(net))}</strong><strong>{margin.toFixed(1)}%</strong></div></section></main></div></div>
}
export default FinancePLApp;
