import { useState } from 'react';
import './finance.css';

type Category={id:string;name:string;type:'Receita'|'Despesa';active:boolean};
type Mode='create'|'view'|'edit';
const INITIAL:Category[]=[{id:'cat-1',name:'Assessoria',type:'Receita',active:true},{id:'cat-2',name:'Renovação',type:'Receita',active:true},{id:'cat-3',name:'Taxas consulares',type:'Despesa',active:true},{id:'cat-4',name:'Serviços terceiros',type:'Despesa',active:true},{id:'cat-5',name:'Marketing',type:'Despesa',active:true},{id:'cat-6',name:'Outros',type:'Despesa',active:true}];
const NAV=[['Dashboard','/crm'],['CRM','/crm/relacionamento'],['Atendimentos','/crm/atendimentos'],['Tarefas','/crm/tarefas'],['Agenda','/crm/agenda'],['Financeiro','/crm/financeiro'],['Relatórios','/crm/relatorios'],['Configurações','/crm/configuracoes']];
function base(){return import.meta.env.BASE_URL.replace(/\/$/,'')}
function href(p:string){return `${base()}${p}`}
function Shell({children}:{children:React.ReactNode}){return <div className="crm-shell finance-shell"><aside className="crm-sidebar"><a className="crm-brand" href={href('/crm')}><span className="crm-brand-mark"><i/><b/></span><span><strong>VISA FÁCIL</strong><small>CRM · Relacionamento</small></span></a><div className="crm-sidebar-accent"><i/><i/><i/></div><span className="crm-sidebar-label">OPERAÇÃO</span><nav>{NAV.map(([l,p])=><a key={p} className={p==='/crm/financeiro'?'is-active':''} href={href(p)}>{l}</a>)}</nav></aside><div className="crm-workspace">{children}</div></div>}
function CategoryModal({mode,item,onClose,onSave}:{mode:Mode;item?:Category;onClose:()=>void;onSave:(v:Omit<Category,'id'>)=>void}){const [name,setName]=useState(item?.name??'');const [type,setType]=useState<'Receita'|'Despesa'>(item?.type??'Receita');const [active,setActive]=useState(item?.active??true);if(mode==='view'&&item)return <div className="finance-modal-backdrop"><div className="finance-view-modal"><header><div><span>CATEGORIA FINANCEIRA</span><h2>{item.name}</h2><p>Visualização do registro</p></div><button onClick={onClose}>×</button></header><section className="finance-view-body"><div className="finance-view-grid"><div><span>Nome</span><strong>{item.name}</strong></div><div><span>Tipo</span><strong>{item.type}</strong></div><div><span>Status</span><strong>{item.active?'Ativa':'Inativa'}</strong></div></div></section><footer><button className="crm-btn-secondary" onClick={onClose}>Fechar</button></footer></div></div>;return <div className="finance-modal-backdrop"><div className="finance-form-modal"><header><div><span>{mode==='create'?'CRIAR CATEGORIA':'EDITAR CATEGORIA'}</span><h2>{mode==='create'?'Nova categoria financeira':'Editar categoria financeira'}</h2></div><button onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();if(name.trim())onSave({name:name.trim(),type,active})}}><div className="finance-form-grid"><label><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label><span>Tipo</span><select value={type} onChange={e=>setType(e.target.value as any)}><option>Receita</option><option>Despesa</option></select></label><label><span>Status</span><select value={active?'Ativa':'Inativa'} onChange={e=>setActive(e.target.value==='Ativa')}><option>Ativa</option><option>Inativa</option></select></label></div><footer><button type="button" className="crm-btn-secondary" onClick={onClose}>Cancelar</button><button className="crm-btn-primary">Salvar</button></footer></form></div></div>}
export function FinancialCategoriesApp(){const [items,setItems]=useState(INITIAL);const [modal,setModal]=useState<{mode:Mode;item?:Category}>();const [menu,setMenu]=useState<string>();const save=(v:Omit<Category,'id'>)=>{if(modal?.item)setItems(a=>a.map(x=>x.id===modal.item!.id?{...x,...v}:x));else setItems(a=>[{id:crypto.randomUUID(),...v},...a]);setModal(undefined)};const del=(x:Category)=>{if(confirm(`Excluir a categoria “${x.name}”?`))setItems(a=>a.filter(i=>i.id!==x.id))};return <Shell><header className="crm-topbar"><div><small>VISA FÁCIL · CRM</small><h1>Categorias Financeiras</h1><p>Gerencie as categorias utilizadas nos lançamentos financeiros.</p></div><div className="crm-topbar-actions finance-header-actions"><a className="finance-header-nav-button" href={href('/crm/financeiro')}>← Financeiro</a><button className="crm-topbar-primary" onClick={()=>setModal({mode:'create'})}>+ Criar</button></div></header><main className="finance-content"><section className="finance-config-card"><div className="finance-simple-table"><div className="finance-simple-head finance-simple-head--actions"><span>Categoria</span><span>Tipo</span><span>Status</span><span>Ações</span></div>{items.map(x=><div className="finance-simple-row finance-simple-row--actions" key={x.id}><strong>{x.name}</strong><span>{x.type}</span><b className={x.active?'is-active':''}>{x.active?'Ativa':'Inativa'}</b><div className="finance-row-actions"><button className="finance-actions-trigger" onClick={()=>setMenu(menu===x.id?undefined:x.id)}>⋮</button>{menu===x.id&&<div className="finance-actions-menu"><button onClick={()=>setModal({mode:'view',item:x})}>Ver</button><button onClick={()=>setModal({mode:'edit',item:x})}>Editar</button><button className="is-danger" onClick={()=>del(x)}>Excluir</button></div>}</div></div>)}</div></section></main>{modal&&<CategoryModal mode={modal.mode} item={modal.item} onClose={()=>setModal(undefined)} onSave={save}/>}</Shell>}
