import { FormEvent, useMemo, useState } from 'react';
import type { Client } from '../../clients/types/client';
import { ManagementModal } from '../../management/components/ManagementModal';
import type { VisaProcess } from '../../processes/types/process';
import { InteractionForm, INTERACTION_CHANNEL_LABELS } from '../components/InteractionForm';
import { InteractionTimeline } from '../components/InteractionTimeline';
import type { ServiceInteraction } from '../types/interaction';

type InteractionUpdate = Partial<Pick<ServiceInteraction, 'clientId' | 'processId' | 'channel' | 'subject' | 'notes' | 'occurredAt'>>;
type InteractionsPageProps = { clients: Client[]; processes: VisaProcess[]; interactions: ServiceInteraction[]; onCreateInteraction: (input: Omit<ServiceInteraction, 'id'>) => void; onUpdateInteraction: (interactionId: string, patch: InteractionUpdate) => void; showForm: boolean; onCloseForm: () => void; };

export function InteractionsPage({ clients, processes, interactions, onCreateInteraction, onUpdateInteraction, showForm, onCloseForm }: InteractionsPageProps) {
  const [query, setQuery] = useState(''); const [channel, setChannel] = useState<ServiceInteraction['channel'] | 'all'>('all'); const [clientId, setClientId] = useState('all'); const [linkedOnly, setLinkedOnly] = useState(false); const [viewInteraction,setViewInteraction]=useState<ServiceInteraction>(); const [editInteraction,setEditInteraction]=useState<ServiceInteraction>();
  const [editClientId,setEditClientId]=useState(''); const [editProcessId,setEditProcessId]=useState(''); const [editChannel,setEditChannel]=useState<ServiceInteraction['channel']>('whatsapp'); const [editSubject,setEditSubject]=useState(''); const [editNotes,setEditNotes]=useState('');
  const whatsappCount = interactions.filter((interaction) => interaction.channel === 'whatsapp').length; const meetingCount = interactions.filter((interaction) => interaction.channel === 'meeting').length; const emailCount = interactions.filter((interaction) => interaction.channel === 'email').length; const linkedToProcess = interactions.filter((interaction) => interaction.processId).length; const linkedRate = interactions.length ? Math.round((linkedToProcess / interactions.length) * 100) : 0; const latest = interactions[0]; const latestClient = clients.find((client) => client.id === latest?.clientId);
  const filteredInteractions = useMemo(() => { const normalized = query.trim().toLowerCase(); return interactions.filter((interaction) => { const client = clients.find((item) => item.id === interaction.clientId); const process = processes.find((item) => item.id === interaction.processId); const matchesQuery = !normalized || `${client?.fullName ?? ''} ${interaction.subject} ${interaction.notes} ${process?.category ?? ''}`.toLowerCase().includes(normalized); return matchesQuery && (channel === 'all' || interaction.channel === channel) && (clientId === 'all' || interaction.clientId === clientId) && (!linkedOnly || Boolean(interaction.processId)); }); }, [channel, clientId, clients, interactions, linkedOnly, processes, query]);
  function createInteraction(input:Omit<ServiceInteraction,'id'>){onCreateInteraction(input);onCloseForm()}
  function beginEdit(interaction:ServiceInteraction){setEditInteraction(interaction);setEditClientId(interaction.clientId);setEditProcessId(interaction.processId??'');setEditChannel(interaction.channel);setEditSubject(interaction.subject);setEditNotes(interaction.notes)}
  function saveEdit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editInteraction||!editClientId||editSubject.trim().length<2||editNotes.trim().length<3)return;onUpdateInteraction(editInteraction.id,{clientId:editClientId,processId:editProcessId||undefined,channel:editChannel,subject:editSubject.trim(),notes:editNotes.trim()});setEditInteraction(undefined)}
  const editProcesses=processes.filter((process)=>process.clientId===editClientId);

  return <section className="management-page interaction-page" aria-labelledby="interactions-title">
    <div className="management-page__heading management-page__heading--row"><div><span className="management-eyebrow">Relacionamento</span><h1 id="interactions-title">Atendimentos</h1><p>Use esta área para registrar contatos relevantes fora do fluxo contínuo do VisaChat: reuniões, ligações, e-mails, orientações e decisões importantes.</p></div><div className="interaction-heading-actions"><a className="management-primary-button" href="/app/chat">Abrir VisaChat</a><span className="interaction-live-pill">Histórico da sessão</span></div></div>
    <div className="interaction-channel-banner"><div><span className="management-eyebrow">Dois contextos, uma operação</span><h2>Conversa contínua no VisaChat. Marcos importantes em Atendimentos.</h2><p>O chat concentra troca de mensagens. Esta tela mantém o histórico resumido de eventos que precisam continuar visíveis no processo do cliente.</p></div><a href="/app/chat">Ir para a central de conversas →</a></div>
    <div className="interaction-summary-grid"><article><span>Total</span><strong>{interactions.length}</strong><small>Registros manuais nesta sessão</small></article><article><span>WhatsApp</span><strong>{whatsappCount}</strong><small>Contatos documentados deste canal</small></article><article><span>Reuniões + e-mail</span><strong>{meetingCount + emailCount}</strong><small>{meetingCount} reunião(ões) · {emailCount} e-mail(s)</small></article><article><span>Vinculados</span><strong>{linkedRate}%</strong><small>{linkedToProcess} registro(s) ligado(s) a processo</small></article></div>
    <div className="interaction-overview-grid"><article className="interaction-overview-card"><span className="management-eyebrow">Última movimentação</span>{latest ? <><strong>{latest.subject}</strong><p>{latestClient?.fullName ?? 'Cliente não encontrado'} · {new Date(latest.occurredAt).toLocaleString('pt-BR')}</p></> : <><strong>Nenhum registro manual ainda</strong><p>O histórico começa assim que um atendimento relevante é registrado.</p></>}</article><article className="interaction-overview-card interaction-overview-card--dark"><span className="management-eyebrow">Cobertura operacional</span><strong>{processes.length ? `${linkedToProcess}/${interactions.length || 0}` : '—'}</strong><p>Atendimentos vinculados a processos ajudam a preservar contexto entre relacionamento, documentos e execução.</p></article><article className="interaction-overview-card"><span className="management-eyebrow">Próxima ação</span><strong>{clients.length ? 'Cliente pronto para atendimento' : 'Cadastre o primeiro cliente'}</strong><p>{clients.length ? 'Use o botão do topo para registrar um marco ou abra o VisaChat.' : 'Clientes são o ponto de partida para chat, processos e histórico.'}</p></article></div>
    {clients.length===0&&<div className="interaction-prerequisite"><div><span className="management-eyebrow">Pré-requisito</span><h2>Cadastre um cliente antes do atendimento</h2><p>O histórico precisa estar sempre associado à pessoa atendida.</p></div><a className="management-primary-button" href="/app/clientes">Ir para Clientes</a></div>}
    <section className="interaction-history-card"><div className="interaction-history-card__heading"><div><span className="management-eyebrow">Histórico</span><h2>Linha do tempo operacional</h2></div><span>{filteredInteractions.length} resultado(s)</span></div><div className="interaction-filter-bar"><label><span>Buscar</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cliente, assunto, observação ou processo" /></label><label><span>Canal</span><select value={channel} onChange={(event) => setChannel(event.target.value as ServiceInteraction['channel'] | 'all')}><option value="all">Todos</option>{Object.entries(INTERACTION_CHANNEL_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Cliente</span><select value={clientId} onChange={(event) => setClientId(event.target.value)}><option value="all">Todos</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label className="interaction-filter-check"><input type="checkbox" checked={linkedOnly} onChange={(event) => setLinkedOnly(event.target.checked)} /><span>Somente vinculados a processo</span></label></div><InteractionTimeline clients={clients} processes={processes} interactions={filteredInteractions} onView={setViewInteraction} onEdit={beginEdit} /></section>

    <ManagementModal open={showForm&&clients.length>0} onClose={onCloseForm} eyebrow="Novo registro" title="Registrar atendimento" subtitle="Documente um marco relevante sem sair do histórico."><InteractionForm clients={clients} processes={processes} onCreateInteraction={createInteraction} /></ManagementModal>
    <ManagementModal open={Boolean(viewInteraction)} onClose={()=>setViewInteraction(undefined)} eyebrow="Visualização" title={viewInteraction?.subject??'Atendimento'} size="md">{viewInteraction&&<div className="management-modal-view"><div className="management-modal-view__grid"><div className="management-modal-view__field"><span>Cliente</span><strong>{clients.find((c)=>c.id===viewInteraction.clientId)?.fullName??'Cliente não encontrado'}</strong></div><div className="management-modal-view__field"><span>Canal</span><strong>{INTERACTION_CHANNEL_LABELS[viewInteraction.channel]}</strong></div><div className="management-modal-view__field"><span>Processo</span><strong>{processes.find((p)=>p.id===viewInteraction.processId)?.category??'Sem processo'}</strong></div><div className="management-modal-view__field"><span>Data</span><strong>{new Date(viewInteraction.occurredAt).toLocaleString('pt-BR')}</strong></div><div className="management-modal-view__field management-modal-view__field--full"><span>Registro</span><p>{viewInteraction.notes}</p></div></div><div className="management-form-actions"><button className="management-primary-button" type="button" onClick={()=>{setViewInteraction(undefined);beginEdit(viewInteraction)}}>Editar atendimento</button></div></div>}</ManagementModal>
    <ManagementModal open={Boolean(editInteraction)} onClose={()=>setEditInteraction(undefined)} eyebrow="Editar atendimento" title={editInteraction?.subject??'Atendimento'}><form className="management-form-card" onSubmit={saveEdit}><div className="management-form-grid"><label><span>Cliente</span><select value={editClientId} onChange={(e)=>{setEditClientId(e.target.value);setEditProcessId('')}}>{clients.map((c)=><option key={c.id} value={c.id}>{c.fullName}</option>)}</select></label><label><span>Processo</span><select value={editProcessId} onChange={(e)=>setEditProcessId(e.target.value)}><option value="">Sem processo específico</option>{editProcesses.map((p)=><option key={p.id} value={p.id}>{p.category}</option>)}</select></label><label><span>Canal</span><select value={editChannel} onChange={(e)=>setEditChannel(e.target.value as ServiceInteraction['channel'])}>{Object.entries(INTERACTION_CHANNEL_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Assunto</span><input value={editSubject} onChange={(e)=>setEditSubject(e.target.value)} /></label><label className="management-field--full"><span>Registro</span><textarea rows={4} value={editNotes} onChange={(e)=>setEditNotes(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-secondary-button" type="button" onClick={()=>setEditInteraction(undefined)}>Cancelar</button><button className="management-primary-button" type="submit">Salvar alterações</button></div></form></ManagementModal>
  </section>;
}
