import { FormEvent, useState } from 'react';
import type { Client } from '../../clients/types/client';
import type { VisaProcess } from '../../processes/types/process';
import type { ServiceInteraction } from '../types/interaction';

const channelLabels: Record<ServiceInteraction['channel'], string> = { whatsapp: 'WhatsApp', email: 'E-mail', phone: 'Telefone', meeting: 'Reunião', other: 'Outro' };
type InteractionsPageProps = { clients: Client[]; processes: VisaProcess[]; interactions: ServiceInteraction[]; onCreateInteraction: (input: Omit<ServiceInteraction, 'id'>) => void; };

export function InteractionsPage({ clients, processes, interactions, onCreateInteraction }: InteractionsPageProps) {
  const [clientId, setClientId] = useState(''); const [processId, setProcessId] = useState(''); const [channel, setChannel] = useState<ServiceInteraction['channel']>('whatsapp'); const [subject, setSubject] = useState(''); const [notes, setNotes] = useState('');
  const clientProcesses = processes.filter((process) => process.clientId === clientId);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onCreateInteraction({ clientId, processId: processId || undefined, channel, subject: subject.trim(), notes: notes.trim(), occurredAt: new Date().toISOString() }); setSubject(''); setNotes(''); }
  return <section className="management-page" aria-labelledby="interactions-title"><div className="management-page__heading"><span className="management-eyebrow">Relacionamento</span><h1 id="interactions-title">Atendimentos</h1><p>Histórico operacional de contatos realizados com cada cliente.</p></div><div className="management-session-note">Registro em memória da sessão para validar o fluxo. Integrações de WhatsApp, e-mail e telefonia não são simuladas nesta fase.</div>{clients.length === 0 ? <div className="management-empty-state"><strong>Nenhum cliente disponível.</strong><span>Cadastre um cliente antes de registrar um atendimento.</span><a className="management-inline-link" href="/app/clientes">Ir para Clientes →</a></div> : <form className="management-form-card" onSubmit={submit}><div className="management-form-grid"><label><span>Cliente</span><select required value={clientId} onChange={(e) => { setClientId(e.target.value); setProcessId(''); }}><option value="">Selecione</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label><span>Processo relacionado</span><select value={processId} onChange={(e) => setProcessId(e.target.value)} disabled={!clientId}><option value="">Sem processo específico</option>{clientProcesses.map((process) => <option key={process.id} value={process.id}>{process.category}</option>)}</select></label><label><span>Canal</span><select value={channel} onChange={(e) => setChannel(e.target.value as ServiceInteraction['channel'])}>{Object.entries(channelLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Assunto</span><input required value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Ex.: checklist enviado" /></label><label className="management-field--full"><span>Registro do atendimento</span><textarea rows={4} required value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-primary-button" type="submit">Registrar atendimento</button></div></form>}{interactions.length === 0 ? <div className="management-empty-state"><strong>Nenhum atendimento na sessão.</strong><span>Os registros aparecerão aqui em ordem cronológica.</span></div> : <div className="management-timeline">{interactions.map((interaction) => { const client = clients.find((item) => item.id === interaction.clientId); return <article className="management-timeline__item" key={interaction.id}><span>{channelLabels[interaction.channel]}</span><div><strong>{interaction.subject}</strong><small>{client?.fullName ?? 'Cliente não encontrado'} · {new Date(interaction.occurredAt).toLocaleString('pt-BR')}</small><p>{interaction.notes}</p></div></article>; })}</div>}</section>;
}
