import { useState } from 'react';
import { INITIAL_USERS, INITIAL_ROLES, type UserRecord, type Role, initials, Card, MiniModal, Field } from './settingsShared';

export function UsersTab(){
 const [users,setUsers]=useState(INITIAL_USERS);const [roles,setRoles]=useState(INITIAL_ROLES);const [email,setEmail]=useState('');const [inviteRole,setInviteRole]=useState('Consultor');const [roleModal,setRoleModal]=useState<Role>();const [createRole,setCreateRole]=useState(false);
 const invite=()=>{if(!email.trim())return;setUsers(c=>[...c,{id:crypto.randomUUID(),name:email.split('@')[0],email,role:inviteRole,status:'Pendente'}]);setEmail('')};
 const remove=(id:string)=>setUsers(c=>c.filter(u=>u.id!==id));
 const addRole=(name:string,description:string)=>{setRoles(c=>[...c,{id:crypto.randomUUID(),name,description,permissions:['CRM']}]);setCreateRole(false)};
 const metrics=[['Usuários Ativos',String(users.filter(u=>u.status==='Ativo').length),'♙'],['Convites Pendentes',String(users.filter(u=>u.status==='Pendente').length),'✉'],['Papéis Configurados',String(roles.length),'◈'],['Permissões Totais',String(new Set(roles.flatMap(r=>r.permissions)).size),'⌘']];
 return <><div className="settings-user-metrics">{metrics.map(([l,v,i])=><article key={l}><span>{i} {l}</span><strong>{v}</strong></article>)}</div>
  <Card title="Gerenciar Equipe" description="Gerencie o acesso dos usuários" icon="♙"><div className="settings-invite-row"><input placeholder="Digite o endereço de email" value={email} onChange={e=>setEmail(e.target.value)}/><select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{roles.map(r=><option key={r.id}>{r.name}</option>)}</select><button className="settings-btn settings-btn-primary" onClick={invite}>➤ Convidar</button></div><div className="settings-user-list">{users.map(user=><div className={`settings-user-row ${user.status==='Pendente'?'is-pending':''}`} key={user.id}><span className="settings-user-avatar">{initials(user.name)}</span><div className="settings-user-copy"><strong>{user.name}</strong><p>{user.email}</p></div><select value={user.role} onChange={e=>setUsers(c=>c.map(u=>u.id===user.id?{...u,role:e.target.value}:u))}>{roles.map(r=><option key={r.id}>{r.name}</option>)}</select><select value={user.status} onChange={e=>setUsers(c=>c.map(u=>u.id===user.id?{...u,status:e.target.value as UserRecord['status']}:u))}><option>Ativo</option><option>Inativo</option><option>Pendente</option></select><button className="settings-icon-danger" onClick={()=>remove(user.id)}>×</button></div>)}</div></Card>
  <Card title="Papéis e Permissões" description="Crie e edite papéis com permissões específicas" icon="◈" action={<button className="settings-btn settings-btn-primary" onClick={()=>setCreateRole(true)}>+ Criar Papel</button>}><div className="settings-role-list">{roles.map(role=><div className="settings-role-row" key={role.id}><span className="settings-role-icon">◈</span><div><strong>{role.name}</strong><p>{role.description}</p></div><button className="settings-btn settings-btn-ghost" onClick={()=>setRoleModal(role)}>Ver Permissões ›</button></div>)}</div></Card>
  {roleModal&&<MiniModal title={`Permissões · ${roleModal.name}`} description={roleModal.description} close={()=>setRoleModal(undefined)} footer={<button className="settings-btn settings-btn-primary" onClick={()=>setRoleModal(undefined)}>Concluir</button>}><div className="settings-permission-grid">{['CRM','Atendimentos','Tarefas','Agenda','Financeiro','Marketing','Relatórios','Configurações'].map(p=><label key={p}><input type="checkbox" defaultChecked={roleModal.permissions.includes('Todos os módulos')||roleModal.permissions.includes(p)}/><span>{p}</span></label>)}</div></MiniModal>}
  {createRole&&<CreateRoleModal close={()=>setCreateRole(false)} save={addRole}/>}</>;
}

function CreateRoleModal({close,save}:{close:()=>void;save:(name:string,description:string)=>void}){const [name,setName]=useState('');const [description,setDescription]=useState('');return <MiniModal title="Criar Papel" description="Defina um papel e suas permissões de acesso." close={close} footer={<><button className="settings-btn settings-btn-outline" onClick={close}>Cancelar</button><button className="settings-btn settings-btn-primary" disabled={!name.trim()} onClick={()=>save(name,description)}>Criar Papel</button></>}><div className="settings-form-grid"><Field label="Nome do papel"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Operacional"/></Field><Field label="Descrição"><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descreva o objetivo deste papel"/></Field></div></MiniModal>}

