import { useMemo, useState } from 'react';
import './agenda.css';
import '../marketing/marketing.css';
import './agenda-calendar-reference.css';
import { getAgendaInitialEvents, type AgendaEvent, type AgendaStatus, type AgendaViewMode } from './mocks/agendaMockProvider';

const TYPE_OPTIONS=['Todos','Entrevista consular','Reunião','Follow-up','Prazo documental','Ligação','Outro'];
const STATUS_OPTIONS:Array<'Todos'|AgendaStatus>=['Todos','Confirmado','Pendente','Realizado','Cancelado'];
const MONTHS=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const WEEKDAYS=['DOM','SEG','TER','QUA','QUI','SEX','SÁB'];
const WEEKDAY_INITIALS_MON=['S','T','Q','Q','S','S','D'];
type ModalMode='create'|'view'|'edit';
type AgendaDraft=Omit<AgendaEvent,'id'>;
const EMPTY_DRAFT:AgendaDraft={title:'',type:'Reunião',status:'Pendente',date:'',startTime:'',endTime:'',location:'',city:'',relatedType:'Cliente',relatedName:'',owner:'Administrador',notes:''};

function base(){const b=import.meta.env.BASE_URL.replace(/\/$/,'');return b||''}
function href(path:string){return `${base()}${path}`||path}
function BellIcon(){return <span className="agenda-bell" aria-hidden="true"/>}
function dateIso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function shiftDate(d:Date,view:AgendaViewMode,delta:number){const n=new Date(d);if(view==='dia')n.setDate(n.getDate()+delta);else if(view==='semana')n.setDate(n.getDate()+delta*7);else if(view==='mes')n.setMonth(n.getMonth()+delta);else n.setFullYear(n.getFullYear()+delta);return n}
function periodLabel(d:Date,view:AgendaViewMode){if(view==='dia')return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'});if(view==='mes')return `${MONTHS[d.getMonth()]} de ${d.getFullYear()}`;if(view==='ano')return String(d.getFullYear());const mon=new Date(d);mon.setDate(mon.getDate()-((mon.getDay()+6)%7));const sun=new Date(mon);sun.setDate(mon.getDate()+6);return `${mon.getDate()} — ${sun.getDate()} de ${MONTHS[sun.getMonth()].toLowerCase()} de ${sun.getFullYear()}`}

function AgendaModal({mode,event,onClose,onSave,onEdit}:{mode:ModalMode;event?:AgendaEvent;onClose:()=>void;onSave:(draft:AgendaDraft)=>void;onEdit?:()=>void}){
 const [draft,setDraft]=useState<AgendaDraft>(()=>event?{...event}:EMPTY_DRAFT);const set=(key:keyof AgendaDraft,value:string)=>setDraft(c=>({...c,[key]:value}));
 if(mode==='view'&&event)return <div className="agenda-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="agenda-view-modal"><header><div><span>{event.type}</span><h2>{event.title}</h2><p>Detalhes completos do compromisso</p></div><button onClick={onClose}>×</button></header><div className="agenda-view-status"><b className={`is-${event.status.toLowerCase()}`}>{event.status}</b></div><section><h3>Quando</h3><div className="agenda-view-grid"><div><span>Data</span><strong>{new Date(`${event.date}T12:00:00`).toLocaleDateString('pt-BR')}</strong></div><div><span>Início</span><strong>{event.startTime||'—'}</strong></div><div><span>Fim</span><strong>{event.endTime||'—'}</strong></div><div><span>Responsável</span><strong>{event.owner}</strong></div></div></section><section><h3>Onde</h3><div className="agenda-view-grid"><div><span>Local</span><strong>{event.location||'—'}</strong></div><div><span>Cidade</span><strong>{event.city||'—'}</strong></div></div></section><section><h3>Vínculo com CRM</h3><div className="agenda-view-grid"><div><span>Tipo</span><strong>{event.relatedType}</strong></div><div><span>Contato</span><strong>{event.relatedName||'—'}</strong></div></div></section><section><h3>Observações</h3><p>{event.notes||'Nenhuma observação cadastrada.'}</p></section><footer><button className="crm-btn-secondary" onClick={onClose}>Fechar</button><button className="crm-btn-primary" onClick={onEdit}>Editar</button></footer></div></div>;
 return <div className="agenda-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="agenda-form-modal"><header><div><span>{mode==='create'?'NOVO EVENTO':'EDITAR EVENTO'}</span><h2>{mode==='create'?'Novo evento na agenda':'Editar evento'}</h2><p>Cadastre o compromisso e vincule ao CRM quando necessário.</p></div><button onClick={onClose}>×</button></header><form onSubmit={e=>{e.preventDefault();if(!draft.title.trim()||!draft.date)return;onSave(draft)}}><div className="agenda-form-grid"><label><span>Título</span><input required value={draft.title} onChange={e=>set('title',e.target.value)}/></label><label><span>Tipo</span><select value={draft.type} onChange={e=>set('type',e.target.value)}>{TYPE_OPTIONS.filter(x=>x!=='Todos').map(x=><option key={x}>{x}</option>)}</select></label><label><span>Status</span><select value={draft.status} onChange={e=>set('status',e.target.value)}>{STATUS_OPTIONS.filter(x=>x!=='Todos').map(x=><option key={x}>{x}</option>)}</select></label><label><span>Data</span><input required type="date" value={draft.date} onChange={e=>set('date',e.target.value)}/></label><label><span>Horário início</span><input type="time" value={draft.startTime} onChange={e=>set('startTime',e.target.value)}/></label><label><span>Horário fim</span><input type="time" value={draft.endTime} onChange={e=>set('endTime',e.target.value)}/></label><label><span>Local</span><input value={draft.location} onChange={e=>set('location',e.target.value)}/></label><label><span>Cidade</span><input value={draft.city} onChange={e=>set('city',e.target.value)}/></label><label><span>Tipo de vínculo</span><select value={draft.relatedType} onChange={e=>set('relatedType',e.target.value)}><option>Cliente</option><option>Contato</option><option>Lead</option></select></label><label><span>Contato / Lead / Cliente</span><input value={draft.relatedName} onChange={e=>set('relatedName',e.target.value)}/></label><label><span>Responsável</span><input value={draft.owner} onChange={e=>set('owner',e.target.value)}/></label><label><span>Observações</span><textarea rows={4} value={draft.notes} onChange={e=>set('notes',e.target.value)}/></label></div><footer><button type="button" className="crm-btn-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="crm-btn-primary">Salvar evento</button></footer></form></div></div>;
}

function AgendaCalendar({events,view,referenceDate,open}:{events:AgendaEvent[];view:AgendaViewMode;referenceDate:Date;open:(event:AgendaEvent)=>void}){
 if(view==='dia'){const iso=dateIso(referenceDate);return <section className="marketing-day-view">{Array.from({length:12},(_,i)=>i+8).map(h=><div className="marketing-hour-row" key={h}><time>{String(h).padStart(2,'0')}:00</time><div>{events.filter(e=>e.date===iso&&Number((e.startTime||'00').slice(0,2))===h).map(e=><button key={e.id} onClick={()=>open(e)}>{e.title}<small>{e.type} · {e.status}</small></button>)}</div></div>)}</section>}
 if(view==='semana'){const mon=new Date(referenceDate);mon.setDate(mon.getDate()-((mon.getDay()+6)%7));const days=Array.from({length:7},(_,i)=>{const d=new Date(mon);d.setDate(mon.getDate()+i);return d});return <section className="marketing-week-view"><div className="marketing-week-head"><span/>{days.map(d=><b key={dateIso(d)}>{d.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}</b>)}</div>{Array.from({length:11},(_,i)=>i+8).map(h=><div className="marketing-week-row" key={h}><time>{String(h).padStart(2,'0')}:00</time>{days.map(d=><div key={dateIso(d)}>{events.filter(e=>e.date===dateIso(d)&&Number((e.startTime||'00').slice(0,2))===h).map(e=><button key={e.id} onClick={()=>open(e)}>{e.title}<small>{e.type}</small></button>)}</div>)}</div>)}</section>}
 if(view==='ano')return <YearView referenceDate={referenceDate} events={events}/>;
 const first=new Date(referenceDate.getFullYear(),referenceDate.getMonth(),1);const start=new Date(first);start.setDate(1-first.getDay());const cells=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});return <section className="marketing-month-view"><div className="marketing-month-head">{WEEKDAYS.map(w=><b key={w}>{w}</b>)}</div><div className="marketing-month-grid">{cells.map(d=><div key={dateIso(d)} className={d.getMonth()!==referenceDate.getMonth()?'is-outside':''}><span>{d.getDate()}</span>{events.filter(e=>e.date===dateIso(d)).map(e=><button key={e.id} onClick={()=>open(e)}>{e.title}<small>{e.type}</small></button>)}</div>)}</div></section>
}

function YearView({referenceDate,events}:{referenceDate:Date;events:AgendaEvent[]}){const y=referenceDate.getFullYear(),today=dateIso(new Date());return <div className="marketing-year-reference"><div className="marketing-year-reference__title">{y}</div><div className="marketing-year-reference__grid">{MONTHS.map((name,m)=>{const firstWeekday=new Date(y,m,1).getDay();const lead=(firstWeekday+6)%7;const daysInMonth=new Date(y,m+1,0).getDate();const cells:Array<number|null>=[];for(let i=0;i<lead;i++)cells.push(null);for(let d=1;d<=daysInMonth;d++)cells.push(d);const total=events.filter(e=>{const d=new Date(`${e.date}T00:00:00`);return d.getFullYear()===y&&d.getMonth()===m}).length;return <article className="marketing-year-reference__month" key={name}><h3>{name}</h3><div className="marketing-year-reference__weekdays">{WEEKDAY_INITIALS_MON.map((w,i)=><span key={`${w}-${i}`}>{w}</span>)}</div><div className="marketing-year-reference__days">{cells.map((d,i)=>d===null?<span key={`x-${i}`} className="is-empty"/>:(()=>{const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const has=events.some(e=>e.date===iso);return <span key={iso} className={`${iso===today?'is-today':''} ${has?'has-content':''}`}>{d}</span>})())}</div><p>{total>0?`${total} ${total===1?'compromisso':'compromissos'}`:''}</p></article>})}</div></div>}

export function AgendaApp(){
 const [events,setEvents]=useState<AgendaEvent[]>(()=>getAgendaInitialEvents());const [viewMode,setViewMode]=useState<AgendaViewMode>('semana');const [currentDate,setCurrentDate]=useState(new Date('2026-08-24T12:00:00'));const [query,setQuery]=useState('');const [typeFilter,setTypeFilter]=useState('Todos');const [statusFilter,setStatusFilter]=useState('Todos');const [modal,setModal]=useState<{mode:ModalMode;event?:AgendaEvent}>();const [notificationsOpen,setNotificationsOpen]=useState(false);const [userOpen,setUserOpen]=useState(false);
 const filtered=useMemo(()=>events.filter(e=>`${e.title} ${e.relatedName} ${e.location} ${e.city}`.toLowerCase().includes(query.toLowerCase())&&(typeFilter==='Todos'||e.type===typeFilter)&&(statusFilter==='Todos'||e.status===statusFilter)),[events,query,typeFilter,statusFilter]);
 const save=(draft:AgendaDraft)=>{if(modal?.event)setEvents(c=>c.map(e=>e.id===modal.event?.id?{...e,...draft}:e));else setEvents(c=>[...c,{...draft,id:crypto.randomUUID()}]);setModal(undefined)};
 return <div className="crm-shell agenda-shell" onClick={()=>{if(notificationsOpen)setNotificationsOpen(false);if(userOpen)setUserOpen(false)}}><div className="crm-workspace"><header className="crm-topbar"><div><small>VISA FÁCIL · CRM</small><h1>Agenda</h1><p>Compromissos, entrevistas, reuniões e prazos da operação.</p></div><div className="crm-topbar-actions" onClick={e=>e.stopPropagation()}><button className="crm-topbar-primary" onClick={()=>setModal({mode:'create'})}>+ Novo evento</button><div className="agenda-topbar-menu"><button className="agenda-notification-button" aria-label="Alertas" onClick={()=>{setNotificationsOpen(v=>!v);setUserOpen(false)}}><BellIcon/></button>{notificationsOpen&&<div className="agenda-dropdown"><strong>Notificações</strong><p>Nenhuma notificação no momento.</p></div>}</div><div className="agenda-topbar-menu"><button className="crm-user" onClick={()=>{setUserOpen(v=>!v);setNotificationsOpen(false)}}><span>VF</span><div><strong>Administrador</strong><small>Protótipo frontend</small></div><span className="crm-user-caret">⌄</span></button>{userOpen&&<div className="agenda-dropdown agenda-user-dropdown"><button>Perfil</button><a href={href('/crm/configuracoes')}>Configurações</a><button className="is-danger">Logout</button></div>}</div></div></header><main className="marketing-content agenda-marketing-calendar"><div className="marketing-calendar-toolbar"><button onClick={()=>setCurrentDate(new Date('2026-08-24T12:00:00'))}>Hoje</button><button onClick={()=>setCurrentDate(shiftDate(currentDate,viewMode,-1))}>‹</button><button onClick={()=>setCurrentDate(shiftDate(currentDate,viewMode,1))}>›</button><strong>{periodLabel(currentDate,viewMode)}</strong><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar evento..."/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}>{TYPE_OPTIONS.map(x=><option key={x}>{x}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}>{STATUS_OPTIONS.map(x=><option key={x}>{x}</option>)}</select><div className="marketing-view-switch">{(['dia','semana','mes','ano'] as AgendaViewMode[]).map(v=><button key={v} className={viewMode===v?'is-active':''} onClick={()=>setViewMode(v)}>{v==='mes'?'Mês':v[0].toUpperCase()+v.slice(1)}</button>)}</div></div><AgendaCalendar events={filtered} view={viewMode} referenceDate={currentDate} open={event=>setModal({mode:'view',event})}/></main></div>{modal&&<AgendaModal mode={modal.mode} event={modal.event} onClose={()=>setModal(undefined)} onSave={save} onEdit={()=>setModal(c=>c?.event?{mode:'edit',event:c.event}:c)}/>}</div>
}
