import { useMemo, useState } from 'react';
import './marketing.css';
import mockData from './mocks/marketing.dev.json';

type Section='overview'|'campaigns'|'calendar'|'metrics'|'creative-ai';
type Campaign={id:string;name:string;channel:string;objective:string;status:string;budget:number;spent:number;leads:number;conversions:number;startDate:string;endDate:string};
type CampaignDraft=Omit<Campaign,'id'|'spent'|'leads'|'conversions'>;
type CreativeResult={headline:string;primaryText:string;cta:string;angle:string};
const EMPTY_CAMPAIGN:CampaignDraft={name:'',channel:'Meta Ads',objective:'Geração de leads',status:'Rascunho',budget:0,startDate:'',endDate:''};
const MAIN_NAV=[{label:'Dashboard',href:'/crm',icon:'⌂'},{label:'CRM',href:'/crm/relacionamento',icon:'◎'},{label:'Atendimentos',href:'/crm/atendimentos',icon:'◌'},{label:'Tarefas',href:'/crm/tarefas',icon:'✓'},{label:'Agenda',href:'/crm/agenda',icon:'□'},{label:'Financeiro',href:'/crm/financeiro',icon:'$'}];
const AFTER_NAV=[{label:'Relatórios',href:'/crm/relatorios',icon:'▥'},{label:'Configurações',href:'/crm/configuracoes',icon:'⚙'}];
const MARKETING_NAV=[{label:'Visão Geral',href:'/crm/marketing',section:'overview' as Section},{label:'Campanhas',href:'/crm/marketing/campanhas',section:'campaigns' as Section},{label:'Calendário',href:'/crm/marketing/calendario',section:'calendar' as Section},{label:'Métricas',href:'/crm/marketing/metricas',section:'metrics' as Section},{label:'IA Criativa',href:'/crm/marketing/ia-criativa',section:'creative-ai' as Section}];
function base(){const b=import.meta.env.BASE_URL.replace(/\/$/,'');return b||''}function href(p:string){return `${base()}${p}`||p}
function normalizePath(){const b=base();const p=b&&window.location.pathname.startsWith(b)?window.location.pathname.slice(b.length)||'/':window.location.pathname;return p.replace(/\/+$/,'')||'/'}
function currentSection():Section{const p=normalizePath();if(p.endsWith('/campanhas'))return'campaigns';if(p.endsWith('/calendario'))return'calendar';if(p.endsWith('/metricas'))return'metrics';if(p.endsWith('/ia-criativa'))return'creative-ai';return'overview'}
function Brand(){return <span className="crm-brand-mark" aria-hidden="true"><i/><b/></span>}function Flag(){return <div className="crm-flag" aria-hidden="true"><span className="crm-flag__blue">✦ ✦ ✦<br/> ✦ ✦</span><span className="crm-flag__stripes"/></div>}
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function MarketingApp(){
 const section=currentSection();
 const [marketingOpen,setMarketingOpen]=useState(true);
 const [campaigns,setCampaigns]=useState<Campaign[]>(()=>mockData.campaigns as Campaign[]);
 const [modal,setModal]=useState(false); const [draft,setDraft]=useState<CampaignDraft>(EMPTY_CAMPAIGN);
 const [notificationsOpen,setNotificationsOpen]=useState(false); const [userOpen,setUserOpen]=useState(false);
 const [creative,setCreative]=useState({service:'Visto americano B1/B2',channel:'Instagram',tone:'Direto e confiável',objective:'Gerar leads',audience:'Brasileiros planejando viajar aos Estados Unidos',offer:'Assessoria completa para solicitação de visto'});
 const [creativeResult,setCreativeResult]=useState<CreativeResult[]>([]);
 const totals=useMemo(()=>({budget:campaigns.reduce((s,c)=>s+c.budget,0),spent:campaigns.reduce((s,c)=>s+c.spent,0),leads:campaigns.reduce((s,c)=>s+c.leads,0),conversions:campaigns.reduce((s,c)=>s+c.conversions,0)}),[campaigns]);
 const cpl=totals.leads?totals.spent/totals.leads:0; const conversionRate=totals.leads?totals.conversions/totals.leads*100:0;
 const saveCampaign=()=>{if(!draft.name.trim())return;setCampaigns(c=>[{...draft,id:crypto.randomUUID(),spent:0,leads:0,conversions:0},...c]);setDraft(EMPTY_CAMPAIGN);setModal(false)};
 const generateCreative=()=>{const service=creative.service.trim()||'seu serviço';const audience=creative.audience.trim()||'seu público';const offer=creative.offer.trim()||'uma solução completa';setCreativeResult([
  {headline:`Seu ${service} com mais segurança e menos burocracia`,primaryText:`Planejando sua viagem? A Visa Fácil acompanha ${audience.toLowerCase()} em cada etapa. ${offer}. Fale com nossa equipe e entenda o próximo passo.`,cta:'Fale com um especialista',angle:'Segurança + redução de burocracia'},
  {headline:`Não deixe seu visto para a última hora`,primaryText:`Organize seu processo com orientação especializada. ${offer}. Atendimento claro, acompanhamento e suporte para você avançar com confiança.`,cta:'Quero começar agora',angle:'Urgência + organização'},
  {headline:`Assessoria para ${service}: do início ao acompanhamento`,primaryText:`Conte com suporte especializado para revisar informações, organizar documentos e acompanhar seu processo. Ideal para ${audience.toLowerCase()}.`,cta:'Solicitar atendimento',angle:'Autoridade + acompanhamento'}
 ])};
 const copyText=(text:string)=>navigator.clipboard?.writeText(text);
 const title=section==='overview'?'Marketing':section==='campaigns'?'Campanhas':section==='calendar'?'Calendário de Marketing':section==='metrics'?'Métricas de Marketing':'IA Criativa';
 const subtitle=section==='overview'?'Campanhas, conteúdo e métricas de aquisição.':section==='campaigns'?'Gestão das campanhas de aquisição.':section==='calendar'?'Planejamento e acompanhamento de conteúdo.':section==='metrics'?'Indicadores de desempenho das ações de marketing.':'Geração assistida de ideias e textos para campanhas.';
 return <div className="crm-shell marketing-shell" onClick={()=>{setNotificationsOpen(false);setUserOpen(false)}}><aside className="crm-sidebar"><a className="crm-brand" href={href('/crm')}><Brand/><span><strong>VISA FÁCIL</strong><small>CRM · Relacionamento</small></span></a><div className="crm-sidebar-accent"><i/><i/><i/></div><span className="crm-sidebar-label">OPERAÇÃO</span><nav>{MAIN_NAV.map(i=><a key={i.href} href={href(i.href)}><span>{i.icon}</span>{i.label}</a>)}<div className="marketing-nav-group"><button type="button" className="marketing-nav-parent is-active" onClick={e=>{e.stopPropagation();setMarketingOpen(v=>!v)}}><span>◈</span><b>Marketing</b><i>{marketingOpen?'⌃':'⌄'}</i></button>{marketingOpen&&<div className="marketing-subnav">{MARKETING_NAV.map(i=><a key={i.href} className={section===i.section?'is-active':''} href={href(i.href)}>{i.label}</a>)}</div>}</div>{AFTER_NAV.map(i=><a key={i.href} href={href(i.href)}><span>{i.icon}</span>{i.label}</a>)}</nav><div className="crm-sidebar-footer"><Flag/><a href={href('/')}>← Voltar ao site</a><small>Protótipo · branch dev</small></div></aside><div className="crm-workspace"><header className="crm-topbar"><div><small>VISA FÁCIL · CRM · MARKETING</small><h1>{title}</h1><p>{subtitle}</p></div><div className="crm-topbar-actions" onClick={e=>e.stopPropagation()}>{section==='campaigns'&&<button className="crm-topbar-primary marketing-new" onClick={()=>setModal(true)}>+ Nova campanha</button>}<div className="marketing-menu"><button className="marketing-bell" aria-label="Alertas" onClick={()=>{setNotificationsOpen(v=>!v);setUserOpen(false)}}>♧</button>{notificationsOpen&&<div className="marketing-dropdown"><strong>Notificações</strong><p>Nenhuma notificação no momento.</p></div>}</div><div className="marketing-menu"><button className="crm-user" onClick={()=>{setUserOpen(v=>!v);setNotificationsOpen(false)}}><span>VF</span><div><strong>Administrador</strong><small>Protótipo frontend</small></div><span className="crm-user-caret">⌄</span></button>{userOpen&&<div className="marketing-dropdown marketing-user"><button>Perfil</button><a href={href('/crm/configuracoes')}>Configurações</a><button className="is-danger">Logout</button></div>}</div></div></header><main className="marketing-content">
 {section==='overview'&&<><section className="marketing-kpis"><article><span>Investimento planejado</span><strong>{money(totals.budget)}</strong><small>Campanhas atuais</small></article><article><span>Investimento realizado</span><strong>{money(totals.spent)}</strong><small>Mídia utilizada</small></article><article><span>Leads gerados</span><strong>{totals.leads}</strong><small>Canais monitorados</small></article><article><span>Conversões</span><strong>{totals.conversions}</strong><small>{conversionRate.toFixed(1)}% dos leads</small></article></section><section className="marketing-grid"><article className="marketing-panel"><header><div><span>CAMPANHAS</span><h2>Desempenho atual</h2></div><a href={href('/crm/marketing/campanhas')}>Ver todas</a></header>{campaigns.slice(0,3).map(c=><div className="marketing-summary-row" key={c.id}><div><strong>{c.name}</strong><small>{c.channel} · {c.status}</small></div><span>{c.leads} leads</span><b>{money(c.spent)}</b></div>)}</article><article className="marketing-panel"><header><div><span>AGENDA</span><h2>Próximos conteúdos</h2></div><a href={href('/crm/marketing/calendario')}>Calendário</a></header>{mockData.calendar.map(i=><div className="marketing-summary-row" key={i.id}><div><strong>{i.title}</strong><small>{i.channel} · {i.status}</small></div><b>{new Date(`${i.date}T12:00:00`).toLocaleDateString('pt-BR')}</b></div>)}</article></section></>}
 {section==='campaigns'&&<section className="marketing-table-card"><div className="marketing-table-head"><span>Campanha</span><span>Canal</span><span>Status</span><span>Orçamento</span><span>Gasto</span><span>Leads</span><span>Conversões</span></div>{campaigns.map(c=><div className="marketing-table-row" key={c.id}><div><strong>{c.name}</strong><small>{c.objective}</small></div><span>{c.channel}</span><span><b className="marketing-status">{c.status}</b></span><span>{money(c.budget)}</span><span>{money(c.spent)}</span><strong>{c.leads}</strong><strong>{c.conversions}</strong></div>)}</section>}
 {section==='calendar'&&<section className="marketing-calendar-card">{mockData.calendar.map(i=><article key={i.id}><time>{new Date(`${i.date}T12:00:00`).toLocaleDateString('pt-BR')}</time><div><strong>{i.title}</strong><small>{i.channel}</small></div><b>{i.status}</b></article>)}</section>}
 {section==='metrics'&&<section className="marketing-kpis marketing-kpis--metrics"><article><span>CPL médio</span><strong>{money(cpl)}</strong><small>Custo por lead</small></article><article><span>Taxa de conversão</span><strong>{conversionRate.toFixed(1)}%</strong><small>Leads convertidos</small></article><article><span>ROAS operacional</span><strong>—</strong><small>Receita atribuída ainda não integrada</small></article><article><span>Campanhas ativas</span><strong>{campaigns.filter(c=>c.status==='Ativa').length}</strong><small>Em veiculação</small></article></section>}
 {section==='creative-ai'&&<section className="marketing-ai-layout"><article className="marketing-ai-builder"><header><span>GERADOR CRIATIVO</span><h2>Criar variações de campanha</h2><p>Preencha o contexto para gerar textos de anúncio e ângulos de comunicação.</p></header><div className="marketing-ai-form"><label><span>Serviço</span><input value={creative.service} onChange={e=>setCreative(c=>({...c,service:e.target.value}))}/></label><label><span>Canal</span><select value={creative.channel} onChange={e=>setCreative(c=>({...c,channel:e.target.value}))}><option>Instagram</option><option>Facebook</option><option>Meta Ads</option><option>Google Ads</option><option>YouTube</option></select></label><label><span>Objetivo</span><select value={creative.objective} onChange={e=>setCreative(c=>({...c,objective:e.target.value}))}><option>Gerar leads</option><option>Conversão</option><option>Tráfego</option><option>Reconhecimento</option></select></label><label><span>Tom de voz</span><select value={creative.tone} onChange={e=>setCreative(c=>({...c,tone:e.target.value}))}><option>Direto e confiável</option><option>Consultivo</option><option>Urgente</option><option>Institucional</option></select></label><label className="is-wide"><span>Público</span><input value={creative.audience} onChange={e=>setCreative(c=>({...c,audience:e.target.value}))}/></label><label className="is-wide"><span>Oferta / mensagem principal</span><textarea rows={4} value={creative.offer} onChange={e=>setCreative(c=>({...c,offer:e.target.value}))}/></label></div><footer><button className="crm-btn-primary" onClick={generateCreative}>Gerar 3 variações</button></footer></article><div className="marketing-ai-results">{creativeResult.length===0?<div className="marketing-ai-empty"><strong>Nenhuma variação gerada</strong><p>Preencha o contexto e clique em “Gerar 3 variações”.</p></div>:creativeResult.map((r,index)=><article key={index}><header><span>VARIAÇÃO {index+1}</span><b>{r.angle}</b></header><h3>{r.headline}</h3><p>{r.primaryText}</p><div><strong>CTA: {r.cta}</strong><button onClick={()=>copyText(`${r.headline}\n\n${r.primaryText}\n\n${r.cta}`)}>Copiar texto</button></div></article>)}</div></section>}
 </main></div>{modal&&<div className="marketing-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setModal(false)}}><div className="marketing-modal"><header><div><span>NOVA CAMPANHA</span><h2>Criar campanha</h2><p>Cadastre uma nova campanha de marketing.</p></div><button onClick={()=>setModal(false)}>×</button></header><div className="marketing-form"><label><span>Nome da campanha</span><input value={draft.name} onChange={e=>setDraft(c=>({...c,name:e.target.value}))}/></label><label><span>Canal</span><select value={draft.channel} onChange={e=>setDraft(c=>({...c,channel:e.target.value}))}><option>Meta Ads</option><option>Google Ads</option><option>Instagram</option><option>Facebook</option><option>YouTube</option></select></label><label><span>Objetivo</span><select value={draft.objective} onChange={e=>setDraft(c=>({...c,objective:e.target.value}))}><option>Geração de leads</option><option>Conversões</option><option>Reconhecimento</option><option>Tráfego</option></select></label><label><span>Status</span><select value={draft.status} onChange={e=>setDraft(c=>({...c,status:e.target.value}))}><option>Rascunho</option><option>Agendada</option><option>Ativa</option><option>Pausada</option></select></label><label><span>Orçamento</span><input type="number" min="0" value={draft.budget||''} onChange={e=>setDraft(c=>({...c,budget:Number(e.target.value)}))}/></label><label><span>Data inicial</span><input type="date" value={draft.startDate} onChange={e=>setDraft(c=>({...c,startDate:e.target.value}))}/></label><label><span>Data final</span><input type="date" value={draft.endDate} onChange={e=>setDraft(c=>({...c,endDate:e.target.value}))}/></label></div><footer><button className="crm-btn-secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="crm-btn-primary" onClick={saveCampaign}>Criar campanha</button></footer></div></div>}</div>
}