import { useState } from 'react';
import { ContractDocumentPreview } from './ContractDocumentPreview';
import { CONTRACT_SIGNATURE_LABEL, CONTRACT_STATUS_LABEL, type ContractCategory, type ContractRecord, type ContractTemplate } from './contractTypes';

function money(value:number){return value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function date(value:string){if(!value)return'—';const parsed=new Date(`${value}T12:00:00`);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleDateString('pt-BR')}
function dateTime(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString('pt-BR')}

const TABS=['Informações','Documento','Assinatura','Versões','Histórico'] as const;

export function ContractViewModal({record,category,template,autentiqueState,onClose,onEdit,onDelete}:{record:ContractRecord;category?:ContractCategory;template?:ContractTemplate;autentiqueState:string;onClose:()=>void;onEdit:()=>void;onDelete:()=>void}){
 const [tab,setTab]=useState<(typeof TABS)[number]>('Informações');
 const client=record.parties.find(item=>item.role==='client')??record.parties[0];
 const editable=record.status==='draft'||record.status==='review';
 return <div className="contracts-modal-backdrop" role="presentation" onMouseDown={event=>event.currentTarget===event.target&&onClose()}>
  <section className="contracts-view" role="dialog" aria-modal="true" aria-labelledby="contract-view-title">
   <header className="contracts-view-header"><div><span>CONTRATO</span><h2 id="contract-view-title">{record.title}</h2><p>{category?.label??'Sem categoria'} · {CONTRACT_STATUS_LABEL[record.status]}</p></div><button type="button" aria-label="Fechar" onClick={onClose}>×</button></header>
   <nav className="contracts-view-tabs">{TABS.map(item=><button type="button" key={item} className={tab===item?'is-active':''} onClick={()=>setTab(item)}>{item}{item==='Versões'&&record.versions.length?` (${record.versions.length})`:''}</button>)}</nav>
   <div className="contracts-view-body">
    {tab==='Informações'&&<div className="contracts-view-info"><section className="contracts-detail-grid"><div><span>Status</span><strong>{CONTRACT_STATUS_LABEL[record.status]}</strong></div><div><span>Categoria</span><strong>{category?.label??'—'}</strong></div><div><span>Template</span><strong>{template?.name??'Snapshot preservado'}</strong></div><div><span>Valor</span><strong>{record.value>0?money(record.value):'—'}</strong></div><div><span>Início</span><strong>{date(record.startDate)}</strong></div><div><span>Término</span><strong>{date(record.endDate)}</strong></div><div><span>Destino</span><strong>{record.destination||'—'}</strong></div><div><span>Tipo de visto</span><strong>{record.visaType||'—'}</strong></div></section><section className="contracts-view-section"><h3>Cliente / contratante</h3><div className="contracts-detail-grid"><div><span>Nome</span><strong>{client?.name||'—'}</strong></div><div><span>Origem</span><strong>{client?.source==='crm'?'CRM':'Manual'}</strong></div><div><span>CPF</span><strong>{client?.cpf||'—'}</strong></div><div><span>RG</span><strong>{client?.rg||'—'}</strong></div><div><span>Passaporte</span><strong>{client?.passportNumber||'—'}</strong></div><div><span>E-mail</span><strong>{client?.email||'—'}</strong></div></div></section><section className="contracts-view-section"><h3>Objeto do contrato</h3><p>{record.serviceDescription||'—'}</p>{record.notes&&<><h3>Observações</h3><p>{record.notes}</p></>}</section></div>}
    {tab==='Documento'&&<div className="contracts-document-tab"><div className="contracts-view-section-heading"><div><span>SNAPSHOT DOCUMENTAL</span><h3>Conteúdo preservado na versão atual</h3></div><small>O documento não muda automaticamente quando o template é editado.</small></div><ContractDocumentPreview content={record.documentContent}/></div>}
    {tab==='Assinatura'&&<div className="contracts-signature-tab"><section className="contracts-signature-summary"><div><span>Provedor</span><strong>{record.signatureProvider==='autentique'?'Autentique':'Ainda não enviado'}</strong></div><div><span>Estado documental</span><strong>{CONTRACT_SIGNATURE_LABEL[record.signatureState]}</strong></div><div><span>Integração Autentique</span><strong>{autentiqueState}</strong></div><div><span>ID externo</span><strong>{record.externalDocumentId||'—'}</strong></div></section><section className="contracts-view-section"><h3>Signatários</h3>{record.signers.length?<div className="contracts-view-signers">{record.signers.slice().sort((a,b)=>a.order-b.order).map(signer=><article key={signer.id}><div><strong>{signer.name}</strong><span>{signer.email||'Sem e-mail'} · {signer.role}</span></div><b>{signer.status==='signed'?'Assinado':signer.status==='rejected'?'Rejeitado':signer.status==='expired'?'Expirado':'Pendente'}</b></article>)}</div>:<p>Nenhum signatário cadastrado.</p>}</section><div className="contracts-unavailable-action"><strong>Envio digital protegido</strong><p>O envio para assinatura não é simulado. Ele só será habilitado quando o contrato existir no backend persistente e a integração Autentique estiver conectada.</p><button type="button" disabled>Enviar para assinatura</button></div></div>}
    {tab==='Versões'&&<div className="contracts-version-list">{record.versions.length?record.versions.slice().reverse().map(version=><article key={version.id}><header><div><strong>Versão {version.label}</strong><span>{dateTime(version.createdAt)}</span></div><p>{version.note||'Atualização documental'}</p></header><ContractDocumentPreview content={version.content}/></article>):<div className="contracts-empty-inline">Nenhuma versão registrada.</div>}</div>}
    {tab==='Histórico'&&<div className="contracts-history"><p className="contracts-history-note">Histórico local desta sessão. A trilha de auditoria definitiva será server-side e imutável.</p>{record.audit.slice().reverse().map(event=><article key={event.id}><i/><div><strong>{event.label}</strong><span>{dateTime(event.createdAt)}</span>{event.detail&&<p>{event.detail}</p>}</div></article>)}</div>}
   </div>
   <footer className="contracts-view-footer"><button type="button" className="contracts-danger-button" onClick={onDelete}>Excluir</button><div><button type="button" className="contracts-secondary-button" onClick={onClose}>Fechar</button><button type="button" className="contracts-primary-button" disabled={!editable} title={editable?undefined:'Somente rascunhos e contratos em revisão podem ser editados.'} onClick={onEdit}>Editar</button></div></footer>
  </section>
 </div>;
}
