import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { Client } from '../../clients/types/client';
import { ManagementModal } from '../../management/components/ManagementModal';
import { PROCESS_PRIORITY_LABELS, type ProcessPriority, type VisaProcess } from '../../processes/types/process';
import type { ManagementTask } from '../types/task';

type TaskUpdate = Partial<Pick<ManagementTask, 'title' | 'clientId' | 'processId' | 'dueDate' | 'priority' | 'notes'>>;
type TasksPageProps = { clients: Client[]; processes: VisaProcess[]; tasks: ManagementTask[]; onCreateTask: (input: Omit<ManagementTask, 'id' | 'createdAt'>) => void; onToggleTask: (taskId: string) => void; onUpdateTask: (taskId: string, patch: TaskUpdate) => void; showForm: boolean; onCloseForm: () => void; };
type TaskFilter = 'all' | 'open' | 'overdue' | 'done';
function localDateKey() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`; }

export function TasksPage({ clients, processes, tasks, onCreateTask, onToggleTask, onUpdateTask, showForm, onCloseForm }: TasksPageProps) {
  const [title, setTitle] = useState(''); const [clientId, setClientId] = useState(''); const [processId, setProcessId] = useState(''); const [dueDate, setDueDate] = useState(''); const [priority, setPriority] = useState<ProcessPriority>('normal'); const [notes, setNotes] = useState(''); const [filter, setFilter] = useState<TaskFilter>('all'); const [error, setError] = useState(''); const [viewTask, setViewTask] = useState<ManagementTask>(); const [editTask, setEditTask] = useState<ManagementTask>();
  const [editTitle, setEditTitle] = useState(''); const [editClientId, setEditClientId] = useState(''); const [editProcessId, setEditProcessId] = useState(''); const [editDueDate, setEditDueDate] = useState(''); const [editPriority, setEditPriority] = useState<ProcessPriority>('normal'); const [editNotes, setEditNotes] = useState('');
  useEffect(() => { if (!editTask) return; setEditTitle(editTask.title); setEditClientId(editTask.clientId ?? ''); setEditProcessId(editTask.processId ?? ''); setEditDueDate(editTask.dueDate); setEditPriority(editTask.priority); setEditNotes(editTask.notes); }, [editTask]);
  const availableProcesses = processes.filter((process) => !clientId || process.clientId === clientId); const editAvailableProcesses = processes.filter((process) => !editClientId || process.clientId === editClientId); const today = localDateKey();
  const openCount = tasks.filter((task) => task.status === 'open').length; const doneCount = tasks.length - openCount; const overdueCount = tasks.filter((task) => task.status === 'open' && task.dueDate && task.dueDate < today).length; const todayCount = tasks.filter((task) => task.status === 'open' && task.dueDate === today).length; const urgentCount = tasks.filter((task) => task.status === 'open' && task.priority === 'urgent').length;
  const filteredTasks = useMemo(() => tasks.filter((task) => { if (filter === 'open') return task.status === 'open'; if (filter === 'done') return task.status === 'done'; if (filter === 'overdue') return task.status === 'open' && Boolean(task.dueDate) && task.dueDate < today; return true; }).sort((a,b) => a.status !== b.status ? (a.status === 'open' ? -1 : 1) : !a.dueDate ? 1 : !b.dueDate ? -1 : a.dueDate.localeCompare(b.dueDate)), [filter, tasks, today]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalizedTitle = title.trim(); if (normalizedTitle.length < 2) { setError('Informe uma tarefa objetiva antes de adicionar a pendência.'); return; } onCreateTask({ title: normalizedTitle, clientId: clientId || undefined, processId: processId || undefined, dueDate, priority, status: 'open', notes: notes.trim() }); setTitle(''); setClientId(''); setProcessId(''); setDueDate(''); setNotes(''); setError(''); onCloseForm(); }
  function saveEdit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editTask || editTitle.trim().length < 2) return; onUpdateTask(editTask.id, { title: editTitle.trim(), clientId: editClientId || undefined, processId: editProcessId || undefined, dueDate: editDueDate, priority: editPriority, notes: editNotes.trim() }); setEditTask(undefined); }

  return <section className="management-page tasks-page" aria-labelledby="tasks-title">
    <div className="management-page__heading"><div><span className="management-eyebrow">Execução</span><h1 id="tasks-title">Tarefas</h1><p>Agenda operacional para pendências, prazos e próximos passos vinculados opcionalmente a clientes e processos.</p></div></div>
    <div className="tasks-alert-strip"><div><span className="management-eyebrow">Foco do dia</span><strong>{overdueCount ? `${overdueCount} tarefa(s) atrasada(s)` : todayCount ? `${todayCount} tarefa(s) vencendo hoje` : 'Nenhum prazo crítico hoje'}</strong><p>{urgentCount ? `${urgentCount} tarefa(s) urgente(s) ainda aberta(s).` : 'As prioridades urgentes aparecerão aqui quando existirem.'}</p></div><a href="/app/processos">Ver processos →</a></div>
    <div className="tasks-summary"><article><span>Abertas</span><strong>{openCount}</strong><small>Pendências em execução</small></article><article><span>Atrasadas</span><strong>{overdueCount}</strong><small>Prazo anterior a hoje</small></article><article><span>Hoje</span><strong>{todayCount}</strong><small>Vencimento na data atual</small></article><article><span>Urgentes</span><strong>{urgentCount}</strong><small>Prioridade máxima em aberto</small></article><article><span>Concluídas</span><strong>{doneCount}</strong><small>Finalizadas nesta sessão</small></article></div>
    <div className="management-session-note">Agenda temporária da sessão. Responsáveis, notificações e automações ficam reservados para a futura camada autenticada.</div>
    <section className="tasks-list-card"><div className="tasks-list-card__heading"><div><span className="management-eyebrow">Agenda</span><h2>Pendências operacionais</h2></div><span>{filteredTasks.length} item(ns)</span></div><div className="tasks-filters" aria-label="Filtros de tarefas"><button className={filter === 'all' ? 'is-active' : ''} onClick={() => setFilter('all')} type="button">Todas</button><button className={filter === 'open' ? 'is-active' : ''} onClick={() => setFilter('open')} type="button">Abertas</button><button className={filter === 'overdue' ? 'is-active' : ''} onClick={() => setFilter('overdue')} type="button">Atrasadas</button><button className={filter === 'done' ? 'is-active' : ''} onClick={() => setFilter('done')} type="button">Concluídas</button></div>{filteredTasks.length === 0 ? <div className="management-empty-state"><strong>Nenhuma tarefa neste filtro.</strong><span>As pendências operacionais aparecerão aqui.</span></div> : <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Tarefa</th><th>Vínculo</th><th>Prazo</th><th>Prioridade</th><th>Status</th><th>Ações</th></tr></thead><tbody>{filteredTasks.map((task) => { const client = clients.find((item) => item.id === task.clientId); const process = processes.find((item) => item.id === task.processId); return <tr key={task.id}><td><strong>{task.title}</strong>{task.notes && <small>{task.notes}</small>}</td><td>{client?.fullName ?? '—'}{process && <small>{process.category}</small>}</td><td>{task.dueDate ? new Date(`${task.dueDate}T00:00:00`).toLocaleDateString('pt-BR') : '—'}</td><td>{PROCESS_PRIORITY_LABELS[task.priority]}</td><td><button className={`management-status-button ${task.status === 'done' ? 'is-complete' : ''}`} type="button" onClick={() => onToggleTask(task.id)}>{task.status === 'done' ? 'Concluída' : 'Aberta'}</button></td><td><div className="management-row-actions"><button className="management-row-action" type="button" onClick={() => setViewTask(task)}>Ver</button><button className="management-row-action management-row-action--primary" type="button" onClick={() => setEditTask(task)}>Editar</button></div></td></tr>; })}</tbody></table></div>}</section>

    <ManagementModal open={showForm} onClose={onCloseForm} eyebrow="Nova pendência" title="Adicionar tarefa" subtitle="Registre um próximo passo sem sair da agenda."><form className="management-form-card" onSubmit={submit} noValidate>{error && <div className="management-form-error" role="alert">{error}</div>}<div className="management-form-grid"><label><span>Tarefa</span><input value={title} onChange={(e) => { setTitle(e.target.value); setError(''); }} placeholder="Ex.: revisar DS-160" /></label><label><span>Prazo</span><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label><label><span>Cliente</span><select value={clientId} onChange={(e) => { setClientId(e.target.value); setProcessId(''); }}><option value="">Sem cliente específico</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label><span>Processo</span><select value={processId} onChange={(e) => setProcessId(e.target.value)}><option value="">Sem processo específico</option>{availableProcesses.map((process) => <option key={process.id} value={process.id}>{process.category}</option>)}</select></label><label><span>Prioridade</span><select value={priority} onChange={(e) => setPriority(e.target.value as ProcessPriority)}>{Object.entries(PROCESS_PRIORITY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="management-field--full"><span>Observações</span><textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-secondary-button" type="button" onClick={onCloseForm}>Cancelar</button><button className="management-primary-button" type="submit">Adicionar tarefa</button></div></form></ManagementModal>
    <ManagementModal open={Boolean(viewTask)} onClose={() => setViewTask(undefined)} eyebrow="Visualização" title={viewTask?.title ?? 'Tarefa'} size="md">{viewTask && <div className="management-modal-view"><div className="management-modal-view__grid"><div className="management-modal-view__field"><span>Status</span><strong>{viewTask.status === 'done' ? 'Concluída' : 'Aberta'}</strong></div><div className="management-modal-view__field"><span>Prioridade</span><strong>{PROCESS_PRIORITY_LABELS[viewTask.priority]}</strong></div><div className="management-modal-view__field"><span>Prazo</span><strong>{viewTask.dueDate ? new Date(`${viewTask.dueDate}T00:00:00`).toLocaleDateString('pt-BR') : 'Não definido'}</strong></div><div className="management-modal-view__field"><span>Cliente</span><strong>{clients.find((c) => c.id === viewTask.clientId)?.fullName ?? 'Sem cliente'}</strong></div><div className="management-modal-view__field management-modal-view__field--full"><span>Observações</span><p>{viewTask.notes || 'Sem observações.'}</p></div></div><div className="management-form-actions"><button className="management-primary-button" type="button" onClick={() => { setViewTask(undefined); setEditTask(viewTask); }}>Editar tarefa</button></div></div>}</ManagementModal>
    <ManagementModal open={Boolean(editTask)} onClose={() => setEditTask(undefined)} eyebrow="Editar tarefa" title={editTask?.title ?? 'Tarefa'}><form className="management-form-card" onSubmit={saveEdit}><div className="management-form-grid"><label><span>Tarefa</span><input value={editTitle} onChange={(e) => setEditTitle(e.target.value)} /></label><label><span>Prazo</span><input type="date" value={editDueDate} onChange={(e) => setEditDueDate(e.target.value)} /></label><label><span>Cliente</span><select value={editClientId} onChange={(e) => { setEditClientId(e.target.value); setEditProcessId(''); }}><option value="">Sem cliente específico</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select></label><label><span>Processo</span><select value={editProcessId} onChange={(e) => setEditProcessId(e.target.value)}><option value="">Sem processo específico</option>{editAvailableProcesses.map((process) => <option key={process.id} value={process.id}>{process.category}</option>)}</select></label><label><span>Prioridade</span><select value={editPriority} onChange={(e) => setEditPriority(e.target.value as ProcessPriority)}>{Object.entries(PROCESS_PRIORITY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="management-field--full"><span>Observações</span><textarea rows={3} value={editNotes} onChange={(e) => setEditNotes(e.target.value)} /></label></div><div className="management-form-actions"><button className="management-secondary-button" type="button" onClick={() => setEditTask(undefined)}>Cancelar</button><button className="management-primary-button" type="submit">Salvar alterações</button></div></form></ManagementModal>
  </section>;
}
